### ISSUE TITLE
CASSCF wrong energy for CuH

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#1022]
Hello,
I would like to please ask your help to figure a mistake out from my CuH simulation.
In particular I am performing a CASSCF simulation on a small active space (3 orbitals of irrep A1 and 4 electrons in it).
First of all, I have noted that by using mcscf.sort_mo_by_irrep I get the wrong active space (I would like two doubly occupied orbitals A1 with index number 11 and 14 and one unoccupied orbital A1 with index number 15), while the calculation automatically chooses the orbitals indexed 14, 15, 18.
My first question is then: how does pySCF choose the active space from the function mcscf.sort_mo_by_irrep? Is the function mcscf.sort_mo(...[11,14,15]...)  the only way to force it to choose our preferred orbitals?

Secondly, I am simulating a lot of different active spaces and the final energy is always around -1639.169 (starting from HF energy of -1639.132) _but_ it gets a lot bigger in this particular case with a final (and converged) CASSCF energy of -1639.133.
I am comparing this code's results with the ones from a "home made" Orbital Relaxation code and the latter gives a final energy around -1639.169 in this case too, which makes me suspect that CASSCF is the wrong one.

Could anyone spot the mistake in the code (if there's a mistake)?
Otherwise, could anyone explain why this active space performs so badly compared to the other ones?

This is the code:
```
ncas_CuH = 3					
cas_space_symmetry = {'A1':3}
ne_act = 2

mol = gto.Mole()
mol.build(verbose  = 4,
         atom     = [['Cu',(0,0,0)],['H',(0,0,1.46)]],
         basis    = '6-31g',
         spin     = 0,
         symmetry = True)
          
myhf = scf.ROHF(mol)
Ehf  = myhf.kernel()
	
mycas   = myhf.CASSCF(ncas=ncas_CuH,nelecas=(ne_act,ne_act))
#mo = mcscf.sort_mo_by_irrep(mycas,myhf.mo_coeff,cas_space_symmetry)
mo = mcscf.sort_mo(mycas,myhf.mo_coeff,[11,14,15])
mycas.fcisolver.wfnsym = 'A1'
mycas.frozen = 9																						
Ecasscf = mycas.kernel(mo)[0]
```

Thank yo in advance!

**Comment by jamesETsmith** [comment]
@martinanibbi I'm pretty sure this is because you're giving MO indices to `sort_mo` that are 0-based indexing (when by default it takes 1-based indexing). I would suggest setting `mol.verbose = 5` which will print out information for your current input telling you the symmetry of your selected orbitals, that's how I was able to track this down. That being said when I do that, I get energies than the ones you report as trusted. 

I ran three different calculations (including one to reproduce your code) here are the summary of the results along with the full output files if you're interested. FYI the log files also contain the input files used to run them if you want to reproduce them.
```
==> bad.out <==
i = 23  <i|F|i> =   0.46193899
i = 24  <i|F|i> =   1.21103141
i = 25  <i|F|i> =   2.47753645
i = 26  <i|F|i> =   2.47754572
i = 27  <i|F|i> =   2.49399765
i = 28  <i|F|i> =   2.49404090
i = 29  <i|F|i> =   2.29639149
    CPU time for 1-step CASSCF    236.78 sec, wall time      1.99 sec
CASSCF energy = -1639.13301763219
CASCI E = -1639.13301763219  E(CI) = -7.65618845135714  S^2 = 0.0000000

==> lower_energy.out <==
i = 23  <i|F|i> =   0.42621474
i = 24  <i|F|i> =   1.21737169
i = 25  <i|F|i> =   2.31587160
i = 26  <i|F|i> =   2.31587160
i = 27  <i|F|i> =   2.34650890
i = 28  <i|F|i> =   2.34650890
i = 29  <i|F|i> =   2.50562769
    CPU time for 1-step CASSCF    215.67 sec, wall time      1.77 sec
CASSCF energy = -1639.17175132011
CASCI E = -1639.17175132011  E(CI) = -4.12300165421061  S^2 = 0.0000000

==> matching.out <==
i = 23  <i|F|i> =   0.42325149
i = 24  <i|F|i> =   1.22107255
i = 25  <i|F|i> =   2.30034114
i = 26  <i|F|i> =   2.30034114
i = 27  <i|F|i> =   2.33130151
i = 28  <i|F|i> =   2.33130333
i = 29  <i|F|i> =   2.49773743
    CPU time for 1-step CASSCF    274.72 sec, wall time      2.25 sec
CASSCF energy = -1639.16991743179
CASCI E = -1639.16991743179  E(CI) = -6.54638354480085  S^2 = 0.0000000
```

[bad.log](https://github.com/pyscf/pyscf/files/6830587/bad.log)
[lower_energy.log](https://github.com/pyscf/pyscf/files/6830588/lower_energy.log)
[matching.log](https://github.com/pyscf/pyscf/files/6830589/matching.log)

**Comment by martinanibbi** [comment]
Thank you so much @jamesETsmith, I don't know why but I was convinced that it was 0-based indexed.
Your help is really appreciated, this problem was driving me crazy!
