### ISSUE TITLE
OSError: /home/xieqx/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64_lin/libmkl_avx.so: undefined symbol: mkl_dnn_getTtl_F32

### ISSUE THREAD

**Issue by QuantunHorizons** [pyscf/pyscf#1024]
Dear PySCF developers,
I installed pyscf using pip in centos7:

> (base) [xieqx@~]$pip install git+https://github.com.cnpmjs.org/pyscf/pyscf
Collecting git+https://github.com.cnpmjs.org/pyscf/pyscf
  Cloning https://github.com.cnpmjs.org/pyscf/pyscf to /tmp/pip-req-build-evr5remt
  Running command git clone -q https://github.com.cnpmjs.org/pyscf/pyscf /tmp/pip-req-build-evr5remt
  Running command git submodule update --init --recursive -q
Requirement already satisfied: numpy!=1.16,!=1.17,>1.8 in ./opt/anaconda3/lib/python3.8/site-packages (from pyscf==2.0.0a0) (1.20.1)
Requirement already satisfied: scipy!=1.5.0,!=1.5.1 in ./opt/anaconda3/lib/python3.8/site-packages (from pyscf==2.0.0a0) (1.6.2)
Requirement already satisfied: h5py>=2.6 in ./opt/anaconda3/lib/python3.8/site-packages (from pyscf==2.0.0a0) (2.10.0)
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.8/site-packages (from h5py>=2.6->pyscf==2.0.0a0) (1.15.0)
Building wheels for collected packages: pyscf
  Building wheel for pyscf (setup.py) ... done
  Created wheel for pyscf: filename=pyscf-2.0.0a0-cp38-cp38-linux_x86_64.whl size=53876308 sha256=ab09011da840c49b0e5743c7e1cb82e0e3ba58764ab53b7a298119542be2d0fa
  Stored in directory: /tmp/pip-ephem-wheel-cache-qyfq5999/wheels/a2/f4/28/62f76deea405ac499b92e9118359842821aa4d748c1b89414d
Successfully built pyscf
Installing collected packages: pyscf
Successfully installed pyscf-2.0.0a0

github.com.cnpmjs.org is mirror of github.com.
I'm trying to import pyscf in python, but it fails with:

> (base) [xieqx@~]$python
Python 3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyscf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xieqx/soft/pyscf-1.7.6/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/home/xieqx/soft/pyscf-1.7.6/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/home/xieqx/soft/pyscf-1.7.6/pyscf/lib/numpy_helper.py", line 39, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/home/xieqx/soft/pyscf-1.7.6/pyscf/lib/misc.py", line 68, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/home/xieqx/opt/anaconda3/lib/python3.8/site-packages/numpy/ctypeslib.py", line 148, in load_library
    return ctypes.cdll[libpath]
  File "/home/xieqx/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 456, in __getitem__
    return getattr(self, name)
  File "/home/xieqx/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 451, in __getattr__
    dll = self._dlltype(name)
  File "/home/xieqx/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xieqx/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64_lin/libmkl_avx.so: undefined symbol: mkl_dnn_getTtl_F32
>>>

Any help will be welcome
Thaks in advance
Best

**Comment by bkesk** [comment]
Hi,

I think I had a similar issue in the past when running PySCF (actually, I think it's an anaconda issue) on CentOS 7. The issue had to do with a failed initialization of MKL at run time. In my case, I could fix the problem by preloading the MKL libraries before running pyscf. In your case, this can be done in bash by setting:

export LD_PRELOAD=" /home/xieqx/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64_lin/libmkl_avx.so"

This assumes that the version of MKL that you want is indeed in that path (/home/xieqx/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64_lin) and not, for example, in "/opt/intel/mkl/lib/intel64/".

you can add the line above to your .bashrc file. You may need to add a few other libraries to the expression above if you see a similar error for different libraries, just be sure to separate each entry with ":". Before running pyscf, you will need to run "source ~/.bashrc" or open a new terminal so that 'ld' will actually preload the libraries.

Also, see the following stack exchange thread: 

https://stackoverflow.com/questions/59020503/intel-mkl-error-preventing-me-importing-scipy-in-python

I hope that helps!

**Comment by sunqm** [comment]
Using the MKL library from the recent versions of anaconda and conda do not require to set LD_PRELOAD environment variable. The installation manual https://pyscf.org/install.html?highlight=mkl#using-optimized-blas also documented solutions regarding to the import error
