### ISSUE TITLE
pbc df loads entire df tensor into memory for a given kpoint, leading to OoM for large gamma point calculations

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#1076]
Hello,

I'm working with a large pbc GDF tensor. I generated this tensor for a 216 atom, 1722 electron system (MgO) on a bigmem node (3 TB). I would like to use this tensor as the basis for a highly frozen post-HF calculation, on a 1 TB node, but my jobs have been killed by an OoM error as the post-HF solver, in my case molecular dfccsd, is asking for the fock matrix in the initialization of the eris.

At first, I thought that this error was due to an miscalculation of a block size for reading in the df tensor, but when I trace the execution of the code to where the error occurs, I find that it is occurring at this line:

https://github.com/pyscf/pyscf/blob/29add011b4f41c6475b32f54abfffdb80fd511c6/pyscf/pbc/df/df.py#L934

The code execution that leads up to the OoM error does not seem to be related to the blksize estimation, but seems to be stacking the df tensor in memory? Is this intended behaviour? I spoke with @xwang862 and he said that a calculation with large df tensors, but low memory on the node, can be accomplished by setting max_memory to a value far below the actual memory, but that doesn't seem to have any effect on this particular line, as blksize only enters once j3c successfully initializes:

https://github.com/pyscf/pyscf/blob/29add011b4f41c6475b32f54abfffdb80fd511c6/pyscf/pbc/df/df.py#L686

I have attached the trace log and am happy to help with any other diagnostics.

[trace.txt](https://github.com/pyscf/pyscf/files/7334218/trace.txt)

**Comment by Majokux** [comment]
This Fock-matrix recalculation in `_common_init_`  has caused me much grief before - it's nice in that it allows you to run CCSD on top of DFT or other non converged HF calculations, but if you know that your mean-field is a converged HF calculation, there is no point in recalculating the Fock matrix -  it's simply S.C.e.C^T.S (where S is the AO-overlap, C the MO coefficients and e the MO energies. And it can be quite expensive to build a new Fock matrix, for example if in the meantime you have folded the mean-field from a k-point calculation to a supercell....

So this is not a direct response to your question, but related enough that I will post my way of dealing with it here:
Since I know the converged Fock matrix from my HF calculation, I avoid recalculating it in `ccsd.ao2mo()` by temporarily replacing the mean field methods which are called in `_common_init_` - i.e. `get_veff`, `get_fock`, `make_rdm1`, and `energy_tot` (it might be enough to just replace `get_veff`). So something like this:

```
get_veff_orig = ccsd._scf.get_veff
ccsd._scf.get_veff = lambda *args : <your_veff, i.e. fock-hcore>
eris = cc.ao2mo()
ccsd._scf.get_veff = get_veff_orig
```

This can also be done more elegantly with  a contextmanager, such as `lib.temporary_env`.
I hope this helps... it of course only works if your mean-field is indeed HF, which I assumed here since you mention post-HF calculations.
