### ISSUE TITLE
Slow SCF convergence?

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1121]
It looks like SCF convergence is slower in the current version of PySCF than in previous releases.

For instance, the example calculation on water
```
from pyscf import gto, scf

mol = gto.Mole()
mol.verbose = 4
mol.atom = '''
O 0 0      0
H 0 -2.757 2.587
H 0  2.757 2.587'''
mol.basis = 'ccpvdz'
mol.symmetry = 1
mol.build()

for guess in ['1e', 'atom', 'minao', 'huckel']:
    mf = scf.RHF(mol)
    mf.init_guess = guess
    mf.kernel()
```

takes

- 29 iterations to converge from the `core` guess
- 27 iterations to converge from the `atom` guess
- 17 iterations to converge from the `minao` guess
- 26 iterations to converge from the `huckel` guess

Water in cc-pVDZ should converge in 6-8 iterations. What's happened?!

**Comment by fishjojo** [comment]
I guess you forgot to set the unit to Bohr. But the bond length is still large.

**Comment by jamesETsmith** [comment]
Hey @susilehtola, thanks for bringing this up. What version of PySCF converged faster? (So we can narrow down where the change came from).

Related to @fishjojo's comment, the O-H bonds in the molecule are much longer than their equilibrium bond length so I'm not so surprised that the SCF takes a few iterations. I tried this problem in ORCA 4.2.1 and found that it also took more than 20 iterations to converge using their default SCF settings (i.e. a mixture of level shifting with first order SCF followed by second order SCF without level shifting). So I think PySCF's results are reasonable.

I surveyed a couple of different SCF options (including level shifting since it's used in other programs).

When using your minimum working example as written, almost all options take longer than 20 iterations and the energies often don't agree.

| initial_guess   |   level_shift |   max_scf_iter |   energy (Ha) | scf converged   | stable   |
|:----------------|--------------:|---------------:|--------------:|:----------------|:---------|
| 1e              |          0    |             32 |      -75.2502 | True            | False    |
| 1e              |          0.25 |             46 |      -75.4201 | True            | True     |
| 1e              |          0.5  |             50 |      -75.4218 | False           | True     |
| atom            |          0    |             27 |      -75.4218 | True            | True     |
| atom            |          0.25 |             23 |      -75.4218 | True            | True     |
| atom            |          0.5  |             37 |      -75.4218 | True            | True     |
| minao           |          0    |             17 |      -75.2502 | True            | False    |
| minao           |          0.25 |             19 |      -75.4218 | True            | True     |
| minao           |          0.5  |             24 |      -75.4201 | True            | True     |
| huckel          |          0    |             26 |      -75.2502 | True            | False    |
| huckel          |          0.25 |             35 |      -75.4206 | True            | True     |
| huckel          |          0.5  |             23 |      -75.4201 | True            | True     |

When using the equilibrium water geometry (from the NIST website) I get the data below, which is much more in range with what you suggested as an appropriate number of SCF iterations.

| initial_guess   |   level_shift |   max_scf_iter |   energy (Ha) | scf converged   | stable   |
|:----------------|--------------:|---------------:|--------------:|:----------------|:---------|
| 1e              |          0    |             10 |      -76.0268 | True            | True     |
| 1e              |          0.25 |             12 |      -76.0268 | True            | True     |
| 1e              |          0.5  |             14 |      -76.0268 | True            | True     |
| atom            |          0    |              8 |      -76.0268 | True            | True     |
| atom            |          0.25 |             10 |      -76.0268 | True            | True     |
| atom            |          0.5  |             11 |      -76.0268 | True            | True     |
| minao           |          0    |              8 |      -76.0268 | True            | True     |
| minao           |          0.25 |             10 |      -76.0268 | True            | True     |
| minao           |          0.5  |             11 |      -76.0268 | True            | True     |
| huckel          |          0    |              8 |      -76.0268 | True            | True     |
| huckel          |          0.25 |             10 |      -76.0268 | True            | True     |
| huckel          |          0.5  |             12 |      -76.0268 | True            | True     |


Here's the script I used to generate these in case you want to reproduce any of this data: [mwe.py.txt](https://github.com/pyscf/pyscf/files/7672121/mwe.py.txt)

**Comment by susilehtola** [comment]
> I guess you forgot to set the unit to Bohr. But the bond length is still large.

I didn't even notice that. The example should be fixed....

https://github.com/pyscf/pyscf/blob/master/examples/scf/01-h2o.py

**Comment by susilehtola** [comment]
The same geometry is used in many other examples, as well. 

dft/02-gks.py
gto/10-atom_info.py
gto/11-basis_info.py
gto/12-serialization.py
scf/01-h2o.py
scf/02-ghf.py
scf/02-rohf_uhf.py
scf/03-level_shift.py

I'm not sure I'd call it H2O when the OH distance is 3.78 Å(!)

**Comment by jamesETsmith** [comment]
That's a good catch in those other examples, thanks @susilehtola!

**Comment by susilehtola** [comment]
The odd thing is that the calculations in #1000 don't work anymore, even though they should work....
