### ISSUE TITLE
failed to detect libcint

### ISSUE THREAD

**Issue by AFOEK** [pyscf/pyscf#1152]
I want to install qiskit for may raspberry pi 400, so I followed [this](https://medium.com/qiskit/rasqberry-quantum-computing-is-the-coolest-project-for-raspberry-pi-3f64bec5a133) method. But when I try to install pyscf I got some error :
![image](https://user-images.githubusercontent.com/52521676/148032101-b9ed0308-3a54-4850-93fe-e46402c14e58.png)
It seems it doesn't detect my libcint installation which I already have 
![image](https://user-images.githubusercontent.com/52521676/148032213-61d8fc45-631d-4ad2-96ab-4433d1429324.png)
any walk through or walk around ?

**Comment by jamesETsmith** [comment]
@AFOEK, my guess is that this is happening because you've compiled a new version of `libcint` (> 4) and the older version of PySCF you've asked for searches specifically for `libcint` with a major version of 4. See below:

https://github.com/pyscf/pyscf/blob/7be5e015b2b40181755c71d888449db936604660/setup.py#L319-L322

My suggestion would be try updating your PySCF version to 2.0.1. Alternatively, you could rebuild `libcint` after checkout out an older version (something 4.X).

**Comment by AFOEK** [comment]
so @jamesETsmith I need to downgrade my `libcint` to successfully build `pyscf ` ? since not all version are compatible for raspi. I will try and I will reach out if I get any problem thanks.

**Comment by AFOEK** [comment]
Hi @jamesETsmith I already try the update option I installing but it seems error on Cmake... 
![image](https://user-images.githubusercontent.com/52521676/148326393-ef738f38-98bd-4711-b152-84ea06c04bc9.png)
my cmake version:
`cmake version 3.16.3`

**Comment by hebrewsnabla** [comment]
> @AFOEK that's one option. I think the easiest option would be to update PySCF to 2.0.1 e.g. `pip install --prefer-binary pyscf==2.0.1`

I don't think so. Full support for libcint 5.x was added 11 days ago [in this commit](https://github.com/pyscf/pyscf/commit/a7ce16fd7e13e8323cb146b3b8bdc016fb0078eb), but 2.0.1 was released in November.

**Comment by AFOEK** [comment]
@hebrewsnabla so I need to downgrade `libcint` then to install ?

**Comment by jamesETsmith** [comment]
@hebrewsnabla, you're right that was my mistake. @AFOEK, your options are:

1. Downgrade `libcint` and install PySCF with `pip install --prefer-binary pyscf==1.7.6` (faster option)
2. Keep `libcint` version 5.x install PySCF with `pip install git+https://github.com/pyscf/pyscf` (slower because you'll build PySCF from source using the most recent commit)

**Comment by AFOEK** [comment]
I successfully to install using build from source
