### ISSUE TITLE
Huckel guess fails if mol.cart = True

### ISSUE THREAD

**Issue by jamont137** [pyscf/pyscf#1162]
The following example illustrates the problem:

from pyscf import gto, scf, dft

mol = gto.Mole()
mol.verbose = 4
mol.atom = '''O  0  0.     0
              H  0  -0.757 0.587
              H  0  0.757  0.587''',

mol.basis = '6-31g*'
mol.cart = True
mol.build()

mf = scf.RHF(mol)
mf.init_guess = 'huckel'
mf.kernel()

Traceback ends with

  File "/home/johnm/src/pyscf-2.0.1/pyscf/scf/hf.py", line 563, in _init_guess_huckel_orbitals
    orb_C[abeg:aend,iocc] = at_c[ia][:,iorb]
ValueError: could not broadcast input array from shape (14) into shape (15)

**Comment by susilehtola** [comment]
The origin is the code in `atom_hf.py` that doesn't support cartesian basis sets.

**Comment by jamont137** [comment]
Thanks, I'm not familiar with the code and had no idea where to look.

**Comment by susilehtola** [comment]
The `atom` guess does do a mapping from spherical to cartesian basis functions in `hf.py`, but this is not done in the `huckel` code.

However, `init_guess_by_atom` does the transformation only at the end; the same code cannot be used to fix the `huckel` guess since the representations change in-between.

I think the best fix would be to change the `atom` code so that the transformation already happens in `atom_hf.get_atm_nrhf` since that should be enough to have both `atom` and `huckel` work.

**Comment by susilehtola** [comment]
I made a hacky fix in #1164. I'm not 100% certain it is correct, since the cartesian->spherical transformation is not invertible as there are more cartesians than spherical functions. At least the code runs now, and according to a quick check on the HF molecule in the 6-31G** basis set, the guess energy seems reasonable; `atom` gives -99.6902090327957 while `huckel` gives -99.889697678567 while the converged energy is -99.9784940418246 with bond length 1.1 Å.

**Comment by jamont137** [comment]
Many thanks! I will try it this afternoon.
