### ISSUE TITLE
exxdiv=None is not completely propagated in gamma point pbc/tdscf

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#1187]
The wrapper to take pbc/scf to molecular tdscf,
https://github.com/pyscf/pyscf/blob/14b880cdc4bf7bb64f3989a147c0b04622efc498/pyscf/pbc/tdscf/rhf.py#L31

Creates a temporary environment where `exxdiv=None`, but this setting does not completely go through the molecular tdscf calculation. In particular, the `mo_energy` is taken from the existing quantity `mf.mo_energy`, instead of calculated from the diagonalization of a freshly made Fock AO matrix, like how the `common_init` works in pyscf/cc. In fact, those lines are commented out!

https://github.com/pyscf/pyscf/blob/14b880cdc4bf7bb64f3989a147c0b04622efc498/pyscf/tdscf/rhf.py#L74

**Comment by sunqm** [comment]
TDDFT code calls the get_jk functions to compute the contraction between two-electron integrals and X,Y amplitudes. Setting `exxdiv=None` here is to ensure the special treatment of exxdiv being excluded because get_jk by default utilize the exxdiv settings in mf object. I guess the question here is whether the exxdiv corrections to orbital energies should be excluded when solving TDDFT response equations. To make TDA results consistent with CIS excited states, the exxdiv corrections should be excluded from orbital energy. However, DFT orbital energy gaps can be used as a good estimation for excitation energies. To make the TDDFT excited energies consistent with the orbital energy gaps, the exxdiv correction has to be kept in the orbital energy when computing the A matrix in TDA as the current implementation. @gkc1000 what do you think?

**Comment by gkc1000** [comment]
I do not know if there is a completely consistent way to do this theoretically.  With correlated methods, the problem is the following: let's say the method depends on H = h + V. Then there is no exxdiv correction to H, since K does not explicitly appear. However, if we rewrite H in normal ordered form, then H = const + F + W. Then one *might* expect exxdiv to apply to the K part of F, but it actually changes the results. My guess is that if the correlated theory does not involve any (vv|vv) integrals - as is true for MP2 and TD-HF-TDA then modifying H -> const + F + exxdiv + W can in practice improve the results.

From a user/code perspective, it is probably least surprising to the user to simply propagate the mf exxdiv option always. Then, this will yield some "wrong" results for correlated methods, e.g. FCI with exxdiv=ws would make no sense. However, correlated methods should probably print a warning "Warning: exxdiv != None. This may give an inconsistent definition of the many-body Hamiltonian. Interpret the results with care." This means the user will not be surprised by the behaviour of the code, although they could be surprised by the correctness of the results.

**Comment by verena-neufeld** [comment]
Is this resolved now, @hongzhouye ?

**Comment by hongzhouye** [comment]
I think so. Now in TDSCF the mo energy will be re-calculated using exxdiv = None. Is that what you were asking?

**Comment by verena-neufeld** [comment]
Thanks! I was asking to see whether this issue can be closed. Sounds like it can.
