### ISSUE TITLE
Obtaining the basis of Slater determinants associated to a CISD calculation

### ISSUE THREAD

**Issue by jfraxanet** [pyscf/pyscf#1293]
Hello, 

I am interested in obtaining the result of CISD as a linear combination of Slater determinants.
Therefore, I need the set of coefficients and the Slater determinants they correspond to. 
For now, I managed to obtain the coefficients using:

```
mol = gto.M(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = 'ccpvdz')

myhf = gto.M(atom='H 0 0 0; F 0 0 1.1', basis='6-31g', verbose=0).apply(scf.RHF).run()
myci = ci.CISD(myhf).run()

print('Coeffs CISD' , myci.ci)
```
but I still don't understand how the Slater determinant basis is built. Is there an easy way to obtain that information?

Moreover, at some point I would like to extend this to periodic systems, but I checked and it seems that the CISD calculation is not generalized for the case in which we have k-points, is that true? Is it still possible to still do it using a super cell (at the gamma point), or is it not supported for periodic systems at all?

Thank you in advance!

**Comment by jfraxanet** [comment]
Great! `c0,c1,c2 = myci.cisdvec_to_amplitudes(myci.ci)` is exactly what I needed! Thank you!
I have one more question in that direction.. is it possible to run ci.CISD() using an arbitrary Slater determinant as initial state? (different from the HF determinant).

Regarding periodic systems, I guess I will try at the gamma point first and then see if it is worth trying to implement the k-points..

**Comment by jfraxanet** [comment]
Nice! 
Just to be sure, if for example I want to run CISD on an excited Slater determinant, which in the HF basis (2nd quantization) looks like |1110010>, this would be the vector I have to input with the occupation numbers right? And in this case, the matrix would just be the identity because I am still in the HF basis?

**Comment by tberkel** [comment]
Yes to everything, except:
1. The `mymo_occ` array should have 2's and 0's if you're doing a
spin-restricted calculation. You can use UCISD or GCISD for more general
(lower) spin symmetries. If speed or memory footprint aren't a major issue
for you (e.g., you plan calculations on only moderately sized systems),
then GCISD is the "simplest" one to use, because it works in the basis of
spin orbitals, with occupation 1 or 0.
2. The matrix `mymo_coeff` is the matrix of MO coeffs in the basis of AOs
(not in the basis of HF MOs). If you want to use the HF MOs, but just
change their occupation, then you can leave out the `mo_coeff` kwarg
entirely.

**Comment by jfraxanet** [comment]
I still have some doubts about how to use the CISD function on an Slater determinant different from the HF state. 

So, for example, let's say I run:
` myci = ci.GCISD(myhf, mo_occ=np.array([1,1,1,0,1,0]))`
for a system with 3 MO (6 spin-MO) and 4 electrons. This should give me all possible single and double excitations starting from this state right? But then I am not sure how to retrieve the coefficients of the resulting Slater determinants. If I do `c0,c1,c2 = myci.cisdvec_to_amplitudes(myci.ci)` then:
- Is c0 the coefficient of the HF determinant or the initial state?
- How is c1 determined now? It can't be c1[i,a] for occ->vir because the occupations at the start where different, but the resulting matrix has the same shape as before.
- Same for c2[i,j,a,b]..

Thank you again!

**Comment by Majokux** [comment]
I haven't tried this, but I would suspect that:
`c0` corresponds to the reference determinant, which is in this case not the HF determinant but the single excited determinant, you have implicitly defined with `mo_occ` (there is no way of CISD to know what the true HF determinant is, since you can also pass in custom `mo_coeff`).
`c1` are the single excitations from this reference determinant. It has the same shape as before, since you have the same number of occupied and virtual orbitals. The matrix elements map to different orbitals however. Eg. `c1[0,0]` is the excitation from the lowest ocupied to the lowest virtual orbital (lowest in ordering, which for a HF reference is identical to the energy ordering): before these were orbital 0 and orbital 4, now it would be orbital 0 and orbital 3, the new "lowest" (in ordering) virtual. Same for `c2`.

**Comment by sunqm** [comment]
c1 is a matrix of the single excitation amplitudes, borrowing the language of coupled cluster. c2 is the tensor of the double excitation amplitudes. The basis of c1[p,q] is q_{\alpha}^\dagger p_{\alpha} and the basis for c2[p,q,r,s] is r_{\alpha}^\dagger s_{\beta}^\dagger p_{\alpha} q_{\beta} .  This example https://github.com/pyscf/pyscf/blob/master/examples/ci/20-from_fci.py can help you to convert between the CC amplitude basis and the determinant basis.

**Comment by jfraxanet** [comment]
Thank you for the replies! It is clear now!
