### ISSUE TITLE
Oscillator Strengths for PBC TDDFT

### ISSUE THREAD

**Issue by manassharma07** [pyscf/pyscf#1315]
How can I calculate the oscillator strengths or intensities of the excitations using PBC TDDFT with multiple k-points, considering that the `td.analyze()` and` td.oscillator_strength() `functions don't work for `pyscf.pbc.tdscf.KTDDFT(kmf)`?

**Comment by hebrewsnabla** [comment]
I think #1319 is kind of duplicated so i would talk here.

pbc.tddft.KTDDFT should work for gamma-point (either HF or KS) excitation energy, as stated by [example 22](https://github.com/pyscf/pyscf/blob/master/examples/pbc/22-k_points_tddft.py), although there seems to be some small bug when switching HF to KS, due to incompatibility in numint (easy-to-fix).

For oscillator strength, it should work for gamma-point TDDFT, but there's also some small bug due to shape of mo_occ. For K-point TDDFT, I think that's not implemented.

**Comment by manassharma07** [comment]
Thanks a lot! Could you please also share the bug-fix here for (1) and (2) if the PR may take longer?

**Comment by hebrewsnabla** [comment]
> Thanks a lot! Could you please also share the bug-fix here for (1) and (2) if the PR may take longer?

You can look at #1320
