### ISSUE TITLE
External potential in X2C 

### ISSUE THREAD

**Issue by kshitij-05** [pyscf/pyscf#1418]
How can I add external potential to spin-free X2C core hamiltonian for X2C-SCF in pyscf?

**Comment by xubwa** [comment]
What kind of external potential would you like to add?

**Comment by kshitij-05** [comment]
External electric field

**Comment by kshitij-05** [comment]
[x2c.txt](https://github.com/pyscf/pyscf/files/9552507/x2c.txt)
The ext_e variable is an array of size 3 with the magnitude of the electric field along x, y, and z axes

**Comment by xubwa** [comment]
I'm not sure with how to apply the potential part, but the idea of your code looks good, you just need to change it a little bit since you are currently overriding the entire get_hcore function by doing this
`mf.with_x2c.get_hcore = lambda *args: h`, 
you may do 
```
h_mod = mf.get_hcore() + h
mf.with_x2c.get_hcore = lambda *args: h_mod
```
So that the x2c transformation is retained.

**Comment by kshitij-05** [comment]
Thank you!
