### ISSUE TITLE
Is 'redefined-outer-name' an issue in the coding style?

### ISSUE THREAD

**Issue by autumn-transformation** [pyscf/pyscf#1528]
This is not a bug report. But about coding style preference. 

I am learning Python programming to a higher level. I run a `pylint` for https://raw.githubusercontent.com/pyscf/pyscf/master/pyscf/scf/hf.py

I got 
```
302:14: W0621: Redefining name 'mol' from outer scope (line 2132) (redefined-outer-name)
```
I guess this is about line 302, `def get_hcore(mol):`, `mol` as an argument, the scope is local. Line 2132
```
mol = gto.Mole()
````
`mol` is defined outside the functions, thus the scope is global.

For maintaining and developing a large-scale program, the style may be important. May I know, in-general, do this issue matter and why?

**Comment by sunqm** [comment]
This error is caused by the `if __name__ == '__main__'` block. Some objects are created there globally. They should be the only source of the warning. These code blocks were written in a very early stage of this project. They are gradually removed when refactoring each module.

Creating global variables other than certain constants is a bad practice. This should be avoided for modules newly developed. Reusing names from outer scope is not recommended as the pylint tells. But it is still acceptable IMO if using these names makes code meaningful.

**Comment by autumn-transformation** [comment]
Thank you very much!
