### ISSUE TITLE
Is that possible to optimize structure from numerical graidents?

### ISSUE THREAD

**Issue by AssoliLan** [pyscf/pyscf#1585]
Hi,

  I tried to optimize a molecule from NEVPT2 level
```
from pyscf import gto, scf, mcscf, mrpt
from pyscf.geomopt.geometric_solver import optimize

mf = gto.M(atom='N 0 0 0; N 0 0 1.4', basis='6-31g').apply(scf.RHF).run()
mc = mcscf.CASSCF(mf, 6, 6).run()
mrpt.NEVPT(mc).kernel()

mol_eq = optimize(mrpt, maxsteps=100)
print(mol_eq.atom_coords())
```
and got nuclear gradient not available information. Is that possible to optimize molecule based on numerical gradient?

**Comment by jamesETsmith** [comment]
@AssoliLan, as far as I know, we don't support numerical gradients out of the box. But having said that it shouldn't be too hard to implement (not necessarily efficiently, but still). 

I'd take a look at this example, where you can define a custom function to calculate the energy and gradients at each step https://github.com/pyscf/pyscf/blob/1660abef6dd1e544bd7df42095db706d6d3ec755/examples/geomopt/02-as_pyscf_method.py#L16-L25

For your 1-D example you could even implement something like a [stencil method](https://en.wikipedia.org/wiki/Five-point_stencil) to calculate the gradient. For 3-D structures, I _**think**_ you could use something like `scipy.optimize.approx_fprime`, see the docs [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html). You could likely use `scipy.optimize.approx_fprime` for 1D too, but since I haven't used it before I wanted to mention the stencils which will definitely work.

**Comment by tberkel** [comment]
Adding a few points to @jamesETsmith 's response: 

1. You passed the `mrpt` module to the `optimize()` function, rather than an instance of a certain method (such as `mf` or `mc`). 

2. Not all methods provide "analytic" gradients that can be used to perform geometry optimization. For example, DFT does, but NEVPT2 does not. So if you need NEVPT2 gradients, one option is to calculate the gradients numerically, along the lines @jamesETsmith suggested.
