### ISSUE TITLE
Electron-Electron Repulsion Energy from an RCCSD Wave Function

### ISSUE THREAD

**Issue by stefanvuckovic1** [pyscf/pyscf#1747]
Dear PySCF developers, 

if I have a simple RCCSD calculation, how can I obtain electron-electron repulsion energy pertaining to the resulting RCCSD wave function (V_ee):

```
from pyscf import gto, scf, cc
mol = gto.M(atom='Ne 0 0 0', basis='cc-pvdz')
mf = scf.RHF(mol)
mf.kernel()
calculation
mycc = cc.RCCSD(mf)
mycc.kernel()
```

**Comment by matthew-hennefarth** [comment]
It is probably easier to calculate the electron-electron repulsion by using the fact that 

$V_{ee} = E_{tot} - V_{ne} - K_{e} - V_{nn}$

That is, we subtract off the nuclear-nuclear repulsion, nuclear-electron attraction, and electron kinetic energy energy from the total energy. This way, we only deal with 1-electron terms, rather than messing with 2-electron terms. With that in mind, something like the following should work:

```python
from pyscf import gto, scf, cc
import numpy as np
from functools import reduce

mol = gto.M(atom='Ne 0 0 0', basis='cc-pvdz')
mf = scf.RHF(mol)
mf.kernel()
mycc = cc.RCCSD(mf)
mycc.kernel()

rdm1 = mycc.make_rdm1() # 1-particle reduced density matrix (in MO basis)
h1e = mycc._scf.get_hcore() # 1-electron integrals (in AO basis)

# transform 1-electron integrals from AO->MO basis
h1e = reduce(np.dot, (mycc.mo_coeff.conj().T, h1e, mycc.mo_coeff))

# Contract 1-RDM with 1-electron integrals to get electron
# kinetic energy and electron-nuclear attraction
h1_energy = np.tensordot(h1e, rdm1)

# Subtract 1-electron and nuclear-nuclear energy from total energy 
# to back-calculate the 2-electron energy.
ee_repulsion_energy = mycc.e_tot - h1_energy - mycc._scf.energy_nuc()

print(ee_repulsion_energy)
```

**Comment by susilehtola** [comment]
It depends on what you mean by "electron-electron repulsion" - the Coulomb interaction contains the classical repulsive interaction, as well as the attractive exchange interaction.
