### ISSUE TITLE
how can we know the occupation number of corresponding active orbitals after CASSCF calculation?

### ISSUE THREAD

**Issue by ABQTrap** [pyscf/pyscf#1785]
Dear all,

I'm new to PySCF. I performed the CASSCF calculation, and I hope to know the occupation number of each active orbital, but I can't find the relevant information in the output file.  At the end of output file, I found the line "Density matrix diagonal elements [1.97623986 1.97036138 1.92039966 1.01726661 1.0227256  0.06913497  0.02387192]", are these numbers in square brackets the occupation numbers of active orbitals ? Also, there is no matching information about orbitals and its corresponding occupation number, so I don't know which orbital has the occupation number of 1.97623986. How to obtain this information? Many Thanks.
Below is the input file:
`import h5py
import os
from pyscf import gto, scf, mcscf
from pyscf import lib
from pyscf.tools import molden

mol = gto.Mole()
mol.atom = "/home/triplet-scan-2.4.xyz"
mol.basis= "def2svp"
mol.charge = 1
mol.spin = 2  # spin = alpha -beta, not 2S+1
mol.verbose = 4
mol.max_memory = 20480
mol.build()

mf = scf.RHF(mol).run()
mf.kernel()

mc = mcscf.CASSCF(mf, 7, (5,3))
mc.max_cycle = 500
mc.sorting_mo_energy = False
mc.frozen = 1   # frozen the inner-most 1s electrons
mc.__dict__.update(lib.chkfile.load('triplet-scan-2.4-rohf.hdf5', 'scf'))
mo = mc.sort_mo([25,26,29,34,36,38,87])

mc.chkfile="triplet-scan-2.4-cas87.hdf5"
mc.kernel(mo)

with open('triplet-scan-2.4-cas87.molden', 'w') as f1:
    molden.header(mol, f1)
    molden.orbital_coeff(mol, f1, mc.mo_coeff, ene=mc.mo_energy, occ=mc.mo_occ)

print(mo)`

**Comment by MatthewRHermes** [comment]
The shortest path to the information you are looking for is simply to set `mc.natorb=True` prior to `mc.kernel(mo)`. Under those circumstances, the `Density matrix diagonal elements` line is replaced with a `Natural occ` line that prints out natural-orbital occupation numbers in descending order, and the active-orbital columns of the MO coefficient array (i.e., `mc.mo_coeff[:,mc.ncore:mc.ncore+mc.ncas]`) are the corresponding natural orbitals in the same order.

In the unlikely event that `mc.natorb=True` has a deleterious effect on the convergence of CASSCF, you can instead do the natural-orbital transformation _post facto_ by calling `mc.cas_natorb_()` immediately after `mc.kernel ()`. There will then be both a `Density matrix diagonal elements` line and a `Natural occ` line in your output; you will want the latter.

PySCF canonicalizes the active orbitals by diagonalizing the Fock matrix by default (rather than the density matrix); the word "occupancy" is avoided in the printouts for such orbitals to avoid confusion with the _natural orbital occupancy_.

**Comment by MatthewRHermes** [comment]
Also, maybe you know this, but the guess MOs provided to kernel are not changed in-place. The last line of your input prints the initial guess MO coefficient array, not the converged optimized MO coefficient array (the latter is accessed as `mc.mo_coeff`)

**Comment by ABQTrap** [comment]
Dear Dr. Matthew Hermes, I really appreciate your reply, it's very helpful !
