### ISSUE TITLE
Potential bug in generalized TDDFT/spinor X2C TDDFT

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#1831]
Hi, I recently tried out some two-component tddft functionalities in pyscf and noticed there might be some problem in the current implementation. In principle, if I use a gks reference to do a tddft calculation and don't involve any spin orbit coupling, I should get all singlet and triplet states from a normal rks-tddft calculation. I made a simple example here to demonstrate this problem
```
from pyscf import gto, scf, tddft
mol = gto.M(atom='''
        Cl 0.0 0.0 0.0
        Cl 1.8 0.0 0.0
''',
        basis='def2svp',
        unit='A')
mf = scf.RKS(mol,'pbe')
mf.kernel()
td = mf.TDA()
td.singlet=False
td.nstates=10
e_trip, _ = td.kernel()
td.singlet=True
td.nstates=10
e_sing, _ = td.kernel()

print('GKS-TDDFT')
mf = scf.GKS(mol,'pbe')
mf.kernel()
td = mf.TDA()
td.nstates=20
e, _ = td.kernel()
```
The output I get is
```converged SCF energy = -919.661959801974
Excited State energies (eV)
[ 4.12501912  4.12501912  8.04737914  8.04737914  9.24665838 14.76025357
 14.76025357 15.50539365 18.48949197 18.48949197]
Excited State energies (eV)
[ 5.15609534  5.15609534  9.05915059  9.05915059 12.87068189 15.29182477
 15.29182477 17.46449571 19.38660315 19.38660315]
GKS-TDDFT
converged SCF energy = -919.661959801975  <S^2> = 8.8817842e-15  2S+1 = 1
Excited State energies (eV)
[ 4.12501912  4.12501912  4.57758845  4.57758845  4.57758845  4.57758845
  5.15609534  5.15609534  8.04737914  8.04737914  8.52897941  8.52897941
  8.52897941  8.52897941  9.05915059  9.05915059  9.24665838 10.17312645
 10.17312645 12.87068189]
```
In the last GKS-TDDFT calculation, the 3rd-6th root, 11th-14th root does not show up in any of the rks-tddft calculation.
If not doing TDDFT but doing TDHF, the GHF-TDHF result then recovers the RHF-TDHF singlet and triplet excitations in the absence of spin orbit coupling. Thus, I suspect there might be some problem with GKS-TDDFT itself. Do you have any clues Qiming @sunqm?

**Comment by sunqm** [comment]
They are triplet states, corresponding to the HOMO_alpha -> LUMO_beta and HOMO_beta -> LUMO_alpha excitation. In theory, if you use mcfun functional, the spin-flip excitation triplets in GKS should be degenerated with the triplet states you obtained from RKS-TDDFT. There are four degenerated HOMO orbitals, therefore you get four states. The RKS and UKS LDA implementation are not able to couple spin flip excitation since the spin-flip matrix is not computed. In GKS, the spin-flip terms are computed although their values are zero. Such excitations are also the egienvectors of the GKS response kernel. The HF exchange of TDHF (and TDDFT of hybrid functionals) can couple the spin-flip excitation.

**Comment by xubwa** [comment]
There is no spin-orbit coupling in this calculation, and therefore, the GKS triplet states should be identical with RKS triplet states, since there are two degenerate triplets in RKS case, then in GKS, I should see 6 degenerate states with from root 3 to root 9, there shouldn't be a four-fold degeneracy and a two-fold degeneracy that splits this triplet by over half eV.

**Comment by Haskiy** [comment]
The collinear functional rather than non-collinear functional will be used in the SCF or TDDFT/TDA calculations at the scf object built by  "scf.GKS(mol,'pbe')" , in fact. Correspondingly, the kernel given by collinear functional can not describe the six-fold degeneracy in excited energies.  A noncollinear functional, such as multi-collinear or locally collinear functional, can give this  six-fold degeneracy correctly, with a calculation keyward set as "mf.collinear = 'mcol'". An example is given below.
**print('GKS-TDDFT')
mf = scf.GKS(mol,'pbe')
mf.collinear = 'mcol'
mf.spin_samples = 266 # the number of sample points in spin space
mf.kernel()
td = mf.TDA()
td.nstates=20
e, _ = td.kernel()**
with output
**GKS-TDDFT
converged SCF energy = -919.661959801974  <S^2> = 7.283063e-14  2S+1 = 1
Excited State energies (eV)
[ 4.12501865  4.12501865  4.1250189   4.1250189   4.12501916  4.12501916
  5.15609516  5.15609516  8.04737852  8.04737852  8.04737867  8.04737867
  8.04737882  8.04737882  9.05915017  9.05915017  9.24665744  9.24665861
  9.24665978 12.87068219]**

**Comment by sunqm** [comment]
Related to #1878 . Should be fixed with new MCfun.
