### ISSUE TITLE
Dyson Orbital for IP-EOM-CCSD

### ISSUE THREAD

**Issue by JangidBhavnesh** [pyscf/pyscf#1880]

**Comment by tberkel** [comment]
I can't say anything for sure without implementing and testing, but you'll
have to be careful about spin adaptation. The "correct" implementation will
have to know whether the underlying mean-field calculation with RHF, UHF,
or GHF, because these symmetries are encoded into the l1, l2, r1, r2
amplitudes. The Dyson orbitals show up in the CCSD Green's function, so
perhaps some of the code in
https://github.com/pyscf/pyscf/blob/master/pyscf/cc/momgfccsd.py can be
borrowed. @obackhouse?

**Comment by obackhouse** [comment]
The `v` and `u` in that code are approximations to the CCSD Dyson orbitals, they are exact in the limit of `niter`->infinity but you can't really approach that limit - they might be good enough approximations for you though. You can use the same expressions to get exact ones with a correction vector implementation, we have a code to do this somewhere if @JangidBhavnesh still wants it (he seems to have deleted the contents of this issue so maybe not).

**Comment by JangidBhavnesh** [comment]
> that code are approximations to the CCSD Dyson orbitals, they are exact in the limit of `niter`->infinity but you can't really approach

It would be great if you can point out to that code.

Thank you

**Comment by ssh2** [comment]
@JangidBhavnesh, if you are interested, we have Dyson orbitals implemented for IP/EA-ADC and those are easy to get.

**Comment by obackhouse** [comment]
My mistake @JangidBhavnesh, the approach I had in mind is only sufficient to obtain to dynamic realisation of the Green's function (as far as I can tell), rather than its Dyson orbitals. If you want exact CC Dyson orbitals I'd suggest consulting the literature and you can likely adapt the bra and ket expressions in `pyscf.cc.momgfccsd`, otherwise that code itself is a very convenient route to approximate ones. As @ssh2 mentions though, ADC(3) Dyson orbitals may be a good option depending on your aims.
