### ISSUE TITLE
Gradients for gamma-only PBC SCF

### ISSUE THREAD

**Issue by zltemp** [pyscf/pyscf#1898]
Dear All,

I'm learning about the gradient calculation for PBC SCF. So far I have found the implementation for multiple k cases. I wonder if there is an implementation for gamma point only. Also, are there any examples of the usage of the integrals used for PBC HF gradients, i.e., how to obtain the 2c2e or 3c2e integral with delta (2c2e_ip1 and 3c2e_ip1) in PBC cases? 
Thank you in advance. Any suggestions are welcomed.

Zili

**Comment by sunqm** [comment]
There is an implementation based on GPW (FFTDF in pyscf). Due to the Coulomb divergence, there are no simple APIs to access 2c2e_ip1 and 3c2e_ip1 with PBC. To apply lattice-sum to the 3-center integrals, you can use `pbc.df.incore.aux_e2`. However, this function does not remove the divergent `G=0` component.

**Comment by verena-neufeld** [comment]
Hi @zltemp , thanks for asking this question. Has it been answered?

**Comment by sunqm** [comment]
Gradients for gamma point can be a feature that improve the performance for the general k-point gradients code. However, this feature is not available in pyscf. If you want this feature in pyscf, feel free to reopen the issue and add a "feature request" label
