### ISSUE TITLE
Problem with k_points = cell.get_abs_kpts(kpts)

### ISSUE THREAD

**Issue by pkozlows** [pyscf/pyscf#1932]
I am getting the message
>Exception has occurred: LinAlgError
0-dimensional array given. Array must be at least two-dimensional
  File "/Users/patrykkozlowski/caltech/classes/caltech/f23/ch121b/si/trotting.py", line 44, in <module>
    k_points = cell.get_abs_kpts(kpts)
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

even though my  kpts has ndim 2. 

I have pasted my script below in case someone wants to look
```
import os
import numpy as np
import matplotlib.pyplot as plt
from pyscf.lib import chkfile
from pyscf.pbc.lib.chkfile import load_cell
from ase.dft.kpoints import sc_special_points as special_points
from ase.dft.kpoints import bandpath
from ase.lattice import bulk
import pyscf.pbc.dft as pbcdft


# Set the file path for the checkpoint file
file_path = os.path.join(os.getcwd(), 'chunky.chk')

# Load the cell object
cell = load_cell(file_path)
cell.pbc = [True, True, True]

# Load the checkpoint file
scf_data = chkfile.load(file_path, 'scf')


# Create and populate the KRKS object
kmf = pbcdft.KRKS(cell)
kmf.__dict__.update(scf_data)

ase_cell = bulk('C', 'diamond', a=3.5668)

# Define the special k-points and paths for an FCC structure
points = special_points['fcc']
G = points['G']
X = points['X']
W = points['W']
K = points['K']
L = points['L']
path = bandpath([L, G, X, W, K, G], ase_cell.cell, npoints=50) # note change to bandpath
kpts = path.kpts
kpath, sp_points, labels = path.get_linear_kpoint_axis()



print(kpts.shape)
**# Calculate bands
k_points = cell.get_abs_kpts(kpts)**
e_kn_2 = kmf.get_bands(k_points)[0]

# Adjust for the Fermi level
vbmax = max(e_kn_2[:, cell.nelectron//2-1])
e_kn_2 -= vbmax

au2ev = 27.21139
emin = -1*au2ev
emax = 1*au2ev

# Plotting
plt.figure(figsize=(5, 6))
nbands = cell.nao_nr()
for n in range(nbands):
    plt.plot(kpath, e_kn_2[:, n]*au2ev, color='#4169E1')
for p in sp_points:
    plt.plot([p, p], [emin, emax], 'k-')
plt.plot([0, sp_points[-1]], [0, 0], 'k-')
plt.xticks(sp_points, ['$%s$' % n for n in ['L', r'\Gamma', 'X', 'W', 'K', r'\Gamma']])
plt.axis(xmin=0, xmax=sp_points[-1], ymin=emin, ymax=emax)
plt.xlabel('k-vector')

plt.show()

```

**Comment by tberkel** [comment]
The error is a numpy linalg error, not a pyscf error. So the problem isn't the dimensions of your `kpts` but rather the dimensions of some array that is used inside the `get_abs_kpts()` function. It's almost surely raised at this line:
https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/cell.py#L1390
which means there is a problem with your `a` (cell) matrix. Try `print(cell.lattice_vectors())` ... this should be a two-dimensional array, but I'll bet that it's not. Unfortunately, we can't debug it because we don't have your `chunky.chk` file. If you make a minimal example that has this error, we can help. As a quick guess, you can try adding `cell.build()` after your line `cell.pbc = [True, True, True]`.

**Comment by pkozlows** [comment]
Indeed,
```print(cell.lattice_vectors())``` is giving NaN. I tried:

> As a quick guess, you can try adding `cell.build()` after your line `cell.pbc = [True, True, True]`.

but this did not solve the problem.
I am trying to make a minimal script that I can run without any problems locally, so that when I run something larger on a cluster, I don't encounter any issues.
The code is:

```python
import pyscf.pbc.tools.pyscf_ase as pyscf_ase
import pyscf.pbc.dft as pbcdft
from pyscf.pbc import gto, scf
import os

from ase.lattice import bulk
from ase.dft.kpoints import sc_special_points as special_points
from ase.dft.kpoints import bandpath


ase_cell = bulk('C', 'diamond', a=3.5668)

cell = gto.Cell()
cell.atom = pyscf_ase.ase_atoms_to_pyscf(ase_cell)
cell.a = ase_cell.cell
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.verbose = 1
cell.build(None,None)

kmf = pbcdft.KRKS(cell, cell.make_kpts([2,2,2]))
kmf.xc = 'lda,vwn_rpa'

points = special_points['fcc']
G = points['G']
X = points['X']
W = points['W']
K = points['K']
L = points['L']
path = bandpath([L, G, X, W, K, G], ase_cell.cell, npoints=50) # note change to bandpath
kpts = path.kpts
kpath, sp_points, labels = path.get_linear_kpoint_axis()

# Set the file path to save the checkpoint file in the current working directory
file_path = os.path.join(os.getcwd(), 'chunky.chk')
print("File Path:", file_path)
kmf.chkfile = file_path
my_cell = scf.chkfile.save_cell(cell, file_path)
kmf.kernel()
```
The pbc.chkfile documentation was confusing me a little bit, but if you would recommend some documentation that I should look at, this would be much appreciated! Think you for your patience.

**Comment by pkozlows** [comment]
So, to load my scf data I want with [pyscf.pbc.scf.chkfile.load_scf(chkfile)](https://pyscf.org/pyscf_api_docs/pyscf.pbc.scf.html#pyscf.pbc.scf.chkfile.load_scf), the cell with [pyscf.pbc.lib.chkfile.load_cell(chkfile)](https://pyscf.org/pyscf_api_docs/pyscf.pbc.lib.html#pyscf.pbc.lib.chkfile.load_cell). However, I am confused about how to save the data.

**Comment by tberkel** [comment]
So, the problem seems to be that the ASE `.cell` returns a `Cell()` object that is not JSON serializable. The pyscf `cell.a` parameter is expected to be a (3,3) ndarray. So, a workaround for you is to use the following line:
`cell.a = np.asarray(ase_cell.cell)`

For any other developers following along, we should consider phasing out "native" ASE support, as its become hard to maintain on the PySCF side.
