### ISSUE TITLE
CASSCF with symmetry for B-H throws an error

### ISSUE THREAD

**Issue by jagunther** [pyscf/pyscf#2022]
Hi,

Calculating the CAS(2,2) energy of B-H with `symmetry=True` throws an error. For Li-H or for `symmetry=False` or for CAS(3,2) there is no error. Issue #1548 seemed to be related. Also, I am running PySCF 2.4.0.

Could someone help figure this out? Thanks!

```
from pyscf import gto, scf, mcscf

### CAS(3,2) runs fine
mol1 = gto.M(atom="B 0 0 0; H 1.5 0 0", basis="sto3g", symmetry=True)
mc1 = mcscf.CASSCF(scf.RHF(mol1).run(), 3, 2)
mc1.kernel()

### Li-H runs fine
mol2 = gto.M(atom="Li 0 0 0; H 1.5 0 0", basis="sto3g", symmetry=True)
mc2 = mcscf.CASSCF(scf.RHF(mol2).run(), 2, 2)
mc2.kernel()

### symmetry=False runs fine
mol3 = gto.M(atom="B 0 0 0; H 1.5 0 0", basis="sto3g", symmetry=False)
mc3 = mcscf.CASSCF(scf.RHF(mol3).run(), 2, 2)
mc3.kernel()

### throws error
mol4 = gto.M(atom="B 0 0 0; H 1.5 0 0", basis="sto3g", symmetry=True)
mc4 = mcscf.CASSCF(scf.RHF(mol4).run(), 2, 2)
mc4.kernel()
```

the output is

```
converged SCF energy = -24.7216853309577
/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
CASSCF energy = -24.7615485480989
CASCI E = -24.7615485480989  E(CI) = -1.32807642898465  S^2 = 0.0000000
converged SCF energy = -7.86335762153512
CASSCF energy = -7.88099257585260
CASCI E = -7.88099257585260  E(CI) = -1.09902483008292  S^2 = 0.0000000
converged SCF energy = -24.7216853309577
CASSCF energy = -24.7435717749394
CASCI E = -24.7435717749394  E(CI) = -1.29911474076125  S^2 = 0.0000000
converged SCF energy = -24.7216853309577
Traceback (most recent call last):
  File "/Users/vrn738/PycharmProjects/mrpt2/molecules/BH/casscf_symmetry_issue.py", line 20, in <module>
    mc4.kernel()
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/mcscf/mc1step_symm.py", line 73, in kernel
    _kern(self, mo_coeff,
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 351, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 878, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/mcscf/casci.py", line 608, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/fci/direct_spin1_symm.py", line 781, in kernel
    ci0 = self.get_init_guess(norb, nelec, nroots, hdiag, orbsym, wfnsym_ir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/fci/direct_spin1_symm.py", line 724, in get_init_guess
    ci0 = get_init_guess_cyl_sym(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/fci/direct_spin1_symm.py", line 291, in get_init_guess_cyl_sym
    ca = _cyl_sym_csf2civec(strsa, addra, orbsym, degen_mapping)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/fci/direct_spin1_symm.py", line 348, in _cyl_sym_csf2civec
    u = _cyl_sym_orbital_rotation(orbsym, degen_mapping)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vrn738/PycharmProjects/mrpt2/venv/lib/python3.11/site-packages/pyscf/fci/direct_spin1_symm.py", line 369, in _cyl_sym_orbital_rotation
    u[j,j] = sqrthi
    ~^^^^^
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by verena-neufeld** [comment]
Thanks for posting this issue @jagunther . I'm not an expert on that part of the code but I had a look what the reason is for the failure in the fourth example. Essentially, I think in the fourth example there are two degenerate orbitals (judging from their MO energies from HF) where one of them is part of the active space and the other one is not. Should CAS work in such a case? Feel free to reply here what you think. My guess is maybe not but there could be a clear error message.

To give more details:
===============
The MO energies for BH here are `[-7.35907163 -0.50719311 -0.24802432  0.2619493   0.2619493   0.50582795]`.
`orbsym` is `[0 0 0 2 3 0]`. BH has six electrons so with an active space of (2,2) in the fourth example and so the third and fourth orbital (mo energies -0.24802432,  0.2619493) are in the active space but not the fifth orbital (mo energy 0.2619493). With an active space of (3, 2), like in the first example, or in the LiH case of the second example, a degeneracy is not split like that, so the first and second examples pass.

Specifically, in `direct_spin1_symm.py` in `_cyl_sym_orbital_rotation`, it is assumed that `norb` is larger than the entries in `degen_mapping` which if I understand correctly has a list orbitals `j` that are degenerate with the orbital `i` (https://github.com/pyscf/pyscf/blob/35835bcb950b525aa89df6d8eb6e0f0366627549/pyscf/fci/direct_spin1_symm.py#L362) but when degeneracy is broken by active space, `degen_mapping` links to an orbital that is not part of the active space and the code fails. Maybe the `map_degeneracy` function creating `degen_mapping` https://github.com/pyscf/pyscf/blob/35835bcb950b525aa89df6d8eb6e0f0366627549/pyscf/scf/hf_symm.py#L357 can be called again after the active space if defined. Then a `PointGroupSymmetryError` in that function will be thrown since the degeneracy is broken. This error could be used to stop the pyscf calculation with a CAS that breaks degeneracy. Or, if this is acceptable behaviour, `degen_mapping`  has to be adapted to not link to an orbital that is outside of the active space.

As I said, I'm not that familiar with that part of the code, so there is a chance I misunderstood.

**Comment by jagunther** [comment]
Hi, thanks for taking a look.

You are right, not including all degenerate orbitals is not reasonable. Although it's a bad active space, it's not a completely wrong usage of the CASSCF method I would say. At least a more expressive error like `PointGroupSymmetryError` as you suggest might be helpful. 
In principle I could help and contribute to this, but I would need some guidance.

**Comment by verena-neufeld** [comment]
Thanks to a latest PR by @sunqm, this now fails with a more descriptive error message:
```
pyscf.lib.exceptions.PointGroupSymmetryError: Incomplete 2D-irrep orbitals for cylindrical symmetry.
orbsym = [0 2]. Retry <class 'pyscf.fci.direct_spin1_symm.FCISolver'> with D2h subgroup symmetry.
```

**Comment by jagunther** [comment]
Great! I am closing this issue then.
