### ISSUE TITLE
High-symmetry FCI

### ISSUE THREAD

**Issue by januseriksen** [pyscf/pyscf#203]
Dear @sunqm 

What are the prospects (if any) of using more symmetry than the Abelian D2h and C2v point groups for FCI on, say, linear molecules? If not for performance gains, then for distinguishing between states?
I've briefly talked to @sanshar offline, and he mentioned that this is possible in his DICE code (please correct me if I'm wrong, Sandeep), so perhaps the interoperability between PySCF and DICE may be utilized to achieve exactly this?

Cheers,
Janus

**Comment by gkc1000** [comment]
Hi Janus,

It depends, different options would require more code, though in some cases, not much more code.

1. Higher symmetries with one-dimensional complex representations e.g. Cnv rather than C2v, are simpler than point groups like Ih. 

2. If we restrict ourselves to such point groups, the characters of the irreps are just complex numbers (like k-pt symmetry). Then, in principle all one needs to fully support this to classify wavefunctions and improve performance, is to have support for the complex integrals. Most of pyscf already supports this, but FCI does not. 

3. One can then either (i) extend FCI to support complex integrals, or (ii) extend the FCI basis transformation (in fci.addons.py) to support complex MO's. In principle, for (i) most of this can be done by keeping real and imaginary parts of the wavefunction, and Hamiltonian, separately, and calling the FCI contract_2e function for each part separately.

4. An intermediate strategy is to work with real bases for the complex irrep; this is taking the sine and cosine linear combinations of the e(iphi), e(-iphi) irreps, much like working with px, py, pz orbitals rather than the complex spherical harmonics. In this case, the Hamiltonian still has some symmetry, but it is (slightly) reduced. PySCF would support this almost out of the box, one would only need to write down the orbital transformation to make these real symmetry adapted integrals, and make some small changes to direct_spin0_symm.py, since the #irreps  > 8 in general, in order to benefit from the symmetry in the computation. This transformation is what is done in DICE to my knowledge, and you could use the same orbital transformation script for FCI. However, the determinant bases in this representation no longer transform as pure irreps, so it does not strictly change the problem of classification.

My opinion is 3(i) is the best option to implement. In any case, this can be tagged as a feature request.

**Comment by sanshar** [comment]
HI Janus,
   If you don't want to do any coding you can just use DICE + pyscf (this
combination supports Dinfh and Cinfv symmetry and will allow you to
distinguish degenerate states of different irreps) with a small enough
epsilon to get near exact FCI energies. Cyrus and I have done this several
times and have scripts to essentially automate the entire process. I have
cc'd him and if you need more details we can chat more.

Sandeep.

**Comment by gkc1000** [comment]
Sandeep pointed out that for Cinfv, the orbitals are complex but the integrals are real (but they have 4-fold symmetry).

In that case, if you still want to use FCI, you only need the script to symmetry adapt the orbitals. Then, you can use the FCI routine that works with 4-fold symmetric integrals, fci.direct_nosym. The script to adapt to cylindrical symmetry is in lib/shciscf. Sandeep will follow up below.

**Comment by CyrusUmrigar** [comment]
Hi,
Sandeep's DICE + pyscf combination generates correct integrals, but for large basis sets it sometimes assigns incorrect symmetry labels.  If you do not use those labels, it is no problem of course.  In our code we use them, so I have a fortran program that goes through and fixes the labels (if it can).  I say "if it can" because it seems that sometimes pyscf combines more than just (Lz,-Lz) pairs, though I don't understand why it would do this since pyscf is supposed to work with real spherical harmonics.

Cyrus

**Comment by sanshar** [comment]
Hi cyrus,
  I don't seem to have an example input file with me right now. Can you
please respond with one in this email.

   So essentially if you use pyscf+dice it should just work straight out of
the box with the input that cyrus will post. There might be some issues for
very large basis sets but if that happens then pyscf will complain and
gracefully exit the calculation.

  As Garnet pointed out in his email, if you are willing to hack into the
code and modify it a little bit, it is possible to get fci to use the Lz
symmetry integrals coming from the script in lib/shciscf.

Sandeep.

**Comment by januseriksen** [comment]
Hi Garnet, Sandeep, and Cyrus,

Thanks for all the comments!

If I understand thing correctly, Dooh is considered in DICE through conservation of M_L, in turn by transforming the orbitals from solid to complex spherical harmonics via a unitary transformation to ensure that the final orbitals are eigenfunctions of the L_z operator?

As I believe this is of general interest (use of Dooh/Coov in FCI), I've cooked up a general test case. Sandeep and Cyrus, can you point me to how I should make use of your code in order to make this run with Dooh? I will then make a proper test and add it to PySCF.

Thanks in advance!
/ Janus

********

#!/usr/bin/env python

import numpy as np
from functools import reduce
from pyscf import gto, scf, ao2mo, symm, fci

mol = gto.M(atom='''
N    0.00000000     0.00000000     1.03715729
N    0.00000000     0.00000000    -1.03715729
''', basis='631g', symmetry='Dooh', unit='bohr', verbose=0, max_memory=6000)

mf = scf.RHF(mol)
mf.run()

core_idx = np.arange(2)
ncore = core_idx.size
cas_idx = np.arange(ncore, np.shape(mf.mo_coeff)[1])

e_core = mol.energy_nuc()
hcore = mf.get_hcore()
core_dm = np.dot(mf.mo_coeff[:, core_idx], mf.mo_coeff[:, core_idx].T) * 2
e_core += np.einsum('ij,ji', core_dm, hcore)
corevhf = scf.hf.get_veff(mol, core_dm)
e_core += np.einsum('ij,ji', core_dm, corevhf) * .5
h1e = reduce(np.dot, (mf.mo_coeff[:, cas_idx].T, hcore + corevhf, mf.mo_coeff[:, cas_idx]))
eri = mol.intor('int2e_sph', aosym=4)
h2e = ao2mo.incore.full(eri, mf.mo_coeff[:, cas_idx])

fcisolver = fci.direct_spin0_symm.FCI(mol)
fcisolver.wfnsym = 'A1g'
fcisolver.orbsym = symm.label_orb_symm(mol, mol.irrep_id, mol.symm_orb, mf.mo_coeff[:, cas_idx])
e_fci = fcisolver.kernel(h1e, h2e, cas_idx.size, mol.nelectron - ncore * 2, ecore=e_core)[0]

print('\nE(SCF) = {0:.6f} , E(FCI) = {1:.6f}\n'.format(mf.e_tot, e_fci))

**Comment by januseriksen** [comment]
One more thing, @gkc1000 - if the FCI code, at some point in time, is extended to support complex integrals, one thing that springs to mind is applications in magnetic fields. I'm unsure as to whether PySCF has GIAO support at the moment, but it shouldn't be too difficult to make PySCF challenge the current state-of-the-art in that area, IMO. Anyways, this is somewhat off-topic...

**Comment by sunqm** [comment]
NMR and g-tensor are available at SCF level. GIAO has been considered there.
What quantities do you need from GIAO?

On Fri, Jul 20, 2018 at 01:57:33AM -0700, januseriksen wrote:
> One more thing, @gkc1000 - if the FCI code, at some point in time, is extended
> to support complex integrals, one thing that springs to mind is applications in
> magnetic fields. I'm unsure as to whether PySCF has GIAO support at the moment,
> but it shouldn't be too difficult to make PySCF challenge the current
> state-of-the-art in that area, IMO. Anyways, this is somewhat off-topic...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Dr. Qiming Sun
Division of Chemistry and Chemical Engineering
California Institute of Technology

**Comment by januseriksen** [comment]
@sunqm - again, this was just something that crossed my mind so I haven't put too much thought into it, but I know for sure that benchmark FCI data in strong (~ 1 au) magnetic fields is something that is in very high demand, cf. http://folk.uio.no/helgaker/reprints/Science_337_327_2012.pdf, which also describes the only - to the best of my knowledge - code available. I believe this code uses complex algebra throughout. However, given that just about every symmetry will be lost in this case, FCI calculations are bound to be expensive. At this moment, CCSD(T) is the best that one can routinely apply at such strong field strengths...

**Comment by januseriksen** [comment]
@CyrusUmrigar - I can't seem to find your attachment - any chance you can share the example(s) once more, either here or in an e-mail (jeriksen@uni-mainz.de)?

Thanks,
Janus

**Comment by sanshar** [comment]
Here is an example, which should just run out of the box with pyscf. Note
that the only keyword that was used in this example to enable the use of
dinfh integrals was mch2.fcisolver.useExtraSymm = True

For your purposes you can tighten the epsilon1 schedule to get fci energies
using Dice.

from pyscf import gto, scf, ao2mo, tools, symm, mcscf

from pyscf.future.shciscf import shci

import numpy


b = 1.68


mol = gto.Mole()


mol.build(

verbose = 4,

output = None,

atom = [

    ['Cr',(  0.000000,  0.000000, -b/2)],

    ['Cr',(  0.000000,  0.000000,  b/2)], ],

basis = {'Cr': 'ccpvdzdk', },

symmetry = 1,

)


# Create HF molecule



mf = scf.RHF( mol )


mf.conv_tol = 1e-9


mf.irrep_nelec = {'A1g' : (7,5), 'E1gx' : (3,2), 'E1gy' : (3,2), 'E2gx' :
(1,0), 'E2gy' : (1,0),'A1u' : (7,5), 'E1ux' : (3,2), 'E1uy' : (3,2), 'E2ux\


' : (1,0), 'E2uy' : (1,0)}


#mf.scf()



mf = scf.sfx2c1e(scf.ROHF(mol))

mf.scf()


mch2 = shci.SHCISCF( mf, 12, (6,6) )





mch2.fcisolver.mpiprefix = 'mpirun -np 24' # Turns on mpi.




ncore = {'A1g' : 5, 'E1gx' : 2, 'E1gy' : 2, 'E2gx' : 0, 'E2gy' : 0,'A1u' :
5, 'E1ux' : 2, 'E1uy' : 2, 'E2ux' : 0, 'E2uy' : 0}

ncas = {'A1g' : 2, 'E1gx' : 1, 'E1gy' : 1, 'E2gx' : 1, 'E2gy' : 1,'A1u' :
2, 'E1ux' : 1, 'E1uy' : 1, 'E2ux' : 1, 'E2uy' : 1}

mo = mcscf.sort_mo_by_irrep(mch2, mf.mo_coeff, ncas, ncore)


mch2.fcisolver.prefix = './scratch' # Put some files in scratch




# Eps1 schedule:


mch2.fcisolver.sweep_iter = [ 0, 3]

mch2.fcisolver.sweep_epsilon = [ 1e-3, 1e-5 ]

mch2.fcisolver.maxIter = 20


mch2.fcisolver.useExtraSymm = True

mch2.max_cycle_macro = 50


mch2.mc1step(mo)

**Comment by januseriksen** [comment]
Great, thanks @sanshar.

One thing - you guys haven't actually tried using the L_z symmetry integrals in the pyscf FCI code, right? I guess I would need to call D2htoDinfh in shciscf/shci.py to get the quantities that should enter transformDinfh in lib/shciscf? I'll have a look at it...

**Comment by sanshar** [comment]
No, we have not. You will have to do a bit of hacking but should not be too
much work hopefully.

Sandeep.

**Comment by gkc1000** [comment]
BTW, there is already an example in symm for constructing the Lz symmetry adapted orbitals:

https://github.com/sunqm/pyscf/blob/master/examples/symm/33-lz_adaption.py

**Comment by januseriksen** [comment]
Got it, thanks Garnet, I'd missed that!
Now, out of curiosity, why (i) is this an example and not a feature within pyscf/symm, and (ii) isn't this code more or less identical to that in D2htoDinfh of pyscf/shciscf/shci.py?

**Comment by ndattani** [comment]
Issue #1517 is related. @susilehtola perhaps you can use [symm/33-lz_adaption.py](https://github.com/sunqm/pyscf/blob/master/examples/symm/33-lz_adaption.py) to get the Lz symmetry-adapted orbitals since the FCI code doesn't (yet?) support complex integrals for D_infinity,h molecules out-of-the-box.

**Comment by sunqm** [comment]
In PySCF 2.2, the FCI module can construct symmetry-adapted initial guess wavefunctions. The fully symmetry-adapted implementation is available in PR #1623
