### ISSUE TITLE
CCSD(T) for localized orbitals

### ISSUE THREAD

**Issue by prasanta13** [pyscf/pyscf#2033]
Dear Users and Developers,
I have a few queries,
1. I have performed localization of Canonical HF orbitals. Next, I want to run Localized CCSD(T). Can it be done with PySCF? 
2. With these localized orbitals, I have run the CCSD(T) calculations as shown below example,
```
    mf = scf.RHF(mol)
    mf.kernel()
    hf_nrg = mf.e_tot  
    ccsd = cc.CCSD(mf)
    ccsd.mo_coeff = **matrix**
    ccsd.kernel()[0]
    ccsd_corr_nrg = ccsd.e_corr
    et = ccsd.ccsd_t()
```
Instead of using canonical orbitals, I feed the localized orbitals by this **matrix**
I am getting CCSD energies accurate to 0.03 kJ/mol, but the (T) correction energies deviate from 15-30 kJ/mol (increasing with larger systems). Would anyone be able to give me a suggestion?
3. If my way is correct, then the 1PDM at the CCSD(T) level should be sparser, which is different in my work. Does it mean I have to use a cut-off for not processing the distant orbitals in CCSD(T) calculations?

I have seen this issue, which is different from mine, https://github.com/pyscf/pyscf/issues/1782
Thanking You,
Prasanta

**Comment by tberkel** [comment]
The most important thing is to know that the current CC algorithms in PySCF do not *exploit* locality just because you use localized orbitals. Proper "local CC" methods (such as CIM, PAO, DLPNO, etc.) are not currently available in PySCF. Therefore, you will see the same scaling, and probably a longer execution time due to more iterations, if you use local orbitals.

If for some reason you still want to use local orbitals, that's fine. CCSD is invariant to rotations of occupied or virtual orbitals among themselves, and the CCSD code in PySCF reflects this (your 0.03 kJ/mol agreement is 1e-5 hartree, which is a bit larger than I'd have guessed, but you can tighten the convergence setting to confirm there is no difference).

For non-canonical HF orbitals, perturbative methods like MP2 or CCSD(T) require an iterative solution. To the best of my knowledge, this iterative solution is not implemented for CCSD(T). Therefore, you should not expect the same answer with non-canonical (e.g., localized) orbitals.

**Comment by prasanta13** [comment]
Thank you very much for your prompt, kind, and informative reply. Are these methods, like DLPNO and iterative ones in the feature-requested list?

**Comment by tberkel** [comment]
Yes, versions of local MP2 and local CCSD(T) are in progress and will be added in the future.

**Comment by prasanta13** [comment]
Thank you very much @tberkel . I am eager to use it when it is added. Thanks again.

**Comment by prasanta13** [comment]
One more query,
Is it possible to start a post-HF calculation, say CCSD, from HF 1PDM?
Actually, I have modified the canonical HF 1PDM, and wanted to run CCSD with it.

**Comment by ghb24** [comment]
This package is simple plugin to pyscf, and can perform a cubic/quartic version of local CCSD (mixing ideas of DMET, CIM and PNOs): https://github.com/BoothGroup/Vayesta

**Comment by verena-neufeld** [comment]
Some ideas regarding your restart question: (Note that I'm not sure what you mean by `1PDM`)

- You could pass in MO coefficients when defining the CC instance, as for example this line does: https://github.com/pyscf/pyscf/blob/35835bcb950b525aa89df6d8eb6e0f0366627549/pyscf/cc/__init__.py#L209 . 

- Another option, depending on what you want to do, might be to set up a mean-field calculation, passing in the density matrix, but not running any iterations of the mean-field calculation. That mean-field calculation could then be the starting point for your CC calculation.

**Comment by prasanta13** [comment]
@verena-neufeld Thank you for your suggestions and advice. For the clarification, let me state my intentions.
I have the one-particle reduced density matrix (1PDM) from PySCF Hartree-Fock calculation. It is obtained using mf.make_rdm1(). I have modified this 1PDM and want to run CCSD calculations from the 1PDM. Can it be done?

**Comment by tberkel** [comment]
As @verena-neufeld said, you can't pass the DM directly to CCSD, but you can use it to define a HF object that can then be passed to CCSD, like below.

```
mf = scf.RHF(mol)
mf.kernel()
mydm = mf.make_rdm1()

# modify mydm here

newmf = scf.RHF(mol)
newmf.max_cycle = 0
newmf.kernel(dm0=mydm)
# newmf.mo_coeff are now based on mydm

mycc = cc.CCSD(newmf).run()
```
