### ISSUE TITLE
Is mcscf.CASSCF really so slow/inefficient???

### ISSUE THREAD

**Issue by EvGeGr** [pyscf/pyscf#2113]
Hello,

I am interested in SA2-CASSCF calculations for a large molecule (137 atoms). I started  with the minimal active space, i.e. CAS(2,2).
I expected the whole calculation should take a few minutes. However, only one iteration takes ~5 minutes or longer, and this is using 96 CPUs. Why is it so inefficient? Is there some other, more efficient than default (FCI) solver? (The py file is attached).

Kind regards,
Evgeniy

[cas.tar.gz](https://github.com/pyscf/pyscf/files/14483491/cas.tar.gz)

**Comment by xubwa** [comment]
It's only a minimal active space, the cost of active space fci is negligible. The molecule is not small, even a mean-field calculation may take a while. Using density fitting may accelerate the calculaiton.

**Comment by EvGeGr** [comment]
Thanks! I see. Would using the CC solver improve the efficiency? There is an implementation of CC solver for  CASCI

https://github.com/pyscf/pyscf/blob/master/examples/cc/42-as_casci_fcisolver.py

How can it be modified to be used for mcscf?

**Comment by tberkel** [comment]
No it wouldn't. As @xubwa said, the cost of the active space solver in negligible. The high cost is due to orbital optimization for such a large molecule with many basis functions.

**Comment by xubwa** [comment]
No, cas(2,2) would only require way less than 1 sec on any machine. The majority of time is spent at optimizing orbitals, where integral transformation and fock matrix are performed. If you increase the verbose to 5, you may have an idea on how much time every piece of the algorithm is consumed.   From: Evgeniy GromovSent: Monday, March 4, 2024 12:16 PMTo: pyscf/pyscfCc: Xubo Wang; CommentSubject: Re: [pyscf/pyscf] Is mcscf.CASSCF really so slow/inefficient??? (Issue #2113) Thanks! I see. Would using the CC solver improve the efficiency? There is an implementation of CC solver for CASCIhttps://github.com/pyscf/pyscf/blob/master/examples/cc/42-as_casci_fcisolver.pyHow can it be modified to be used for mcscf?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by EvGeGr** [comment]
Ok, I see, thanks!

**Comment by EvGeGr** [comment]
Hi Verena,

yes, my question has been answered and can be closed.
