### ISSUE TITLE
How to get access to S0, S1, ... states (energies etc.) in state-average mcscf calculation?

### ISSUE THREAD

**Issue by EvGeGr** [pyscf/pyscf#2114]
Hello,

after performing a state-average MCSCF calculation, how would one access a particular state?
For instance, in a 2-state-averaging calculation, to get the energy of the s0 and s1 state, should one do casci like

c = mcscf.CASCI(b, 3, 4)
s0 = c.casci(mo)[0]
s1 = c.casci(mo)[1]

I tried this, but I get only S0 in both cases.

I used this example:

https://github.com/pyscf/pyscf/blob/master/examples/mcscf/15-state_average.py

**Comment by tberkel** [comment]
After state-averaging MCSCF, the energy of the states are stored in `mc.e_states`.

**Comment by EvGeGr** [comment]
Thanks!

**Comment by matthew-hennefarth** [comment]
> mcscf.CASCI(mo)

This is not how the CASCI objects should be run in general. Starting from some `mol` one would typically do the following:

```python
mf = mol.RHF().run()

mc = mcscf.CASCI(mf, ncas, nelecas)
```

Here `ncas` is the number of active orbitals and `nelecas` are the number of active electrons. This gives you a solver for only the ground state. To get excited states, one has to do state-averaging by adding the following lines:

```python
nstates = 2
mc = mc.state_average([1.0/nstates,]*nstates)
```

This will give equal weights for the state averaging. If you want the energies for each state, you access the energies through the `e_states` attribute as such:

```python
mc.run()
print(mc.e_states)
```

Now, if you have `mo`s from a prior calculation, you can use those instead of the RHF MO's for the CASCI by passing them into the `mc.run()` as a kwarg

```python
mc.run(mo)
print(mc.e_states)
```

The S1 state energy will be the first index of the `e_states` attribute.

```python
print(f"S0: {mc.e_states[0]})
print(f"S1: {mc.e_states[1]})
```

And, irregardless of all of this, always make sure that your final states have the correct spin by inspecting the logs for S^2. Since PySCF is by default in slater determinants, it is often that excited states will be of the wrong spin state and one should then use the `.fix_spin_` method (see [here](https://github.com/pyscf/pyscf/blob/a40064009cd3865bce6315d9f87323340e3f343c/examples/mcscf/02-cas_space_spin.py#L34-L35))

**Comment by EvGeGr** [comment]
Many thanks for your response! I'm a bit confused, why is the state-averaging needed here, in the case of mcscf.CASCI? Is it for technical reasons, just to involve many states (rather than one state)? If so, the weights of the states are then not important, are they? I mean, one anyway gets the correct energies with e_states.

**Comment by tberkel** [comment]
You can do state-specific CASCI. I think a complete workflow would look something like this (e.g., (2,2) CASSCF seeking two singlet states, ground and excited):
```
    weights = [0.5,0.5]
    mc = mcscf.CASSCF(mf, 2, 2)
    mc = mcscf.state_average_(mc, weights)
    mc.fcisolver.spin = 0
    mc.fix_spin_(ss=0)
    mc.kernel()
    # energies now appear in mc.e_states

    # if you want more access to states, e.g., from .analyze() ...
    for s in range(len(weights)):
        print("CASCI state =", s)
        ci = mcscf.CASCI(mf, 2, 2).state_specific_(s)
        ci.fcisolver.spin = 0
        ci.fix_spin_(ss=0)
        ci.kernel(mc.mo_coeff)
        ci.analyze()
```

**Comment by EvGeGr** [comment]
Many thanks! Exactly what I need :)

**Comment by verena-neufeld** [comment]
Hi @EvGeGr , thanks! Can this issue be closed or do you have further questions?
