### ISSUE TITLE
How to transform the Hamiltonians between pyscf and psi4?

### ISSUE THREAD

**Issue by thu-wangz17** [pyscf/pyscf#2123]
I find that the Hamiltonians obtained from pyscf and psi4 are different. For example, there will be differences at $l>=1$ for water under `def2-svp` basis. I guess the difference comes from the AOs are expressed in different forms. But the eigenvalues of Hamiltonians from pyscf and psi4 are the same. Thus the Hamiltonians from these two methods could be connected under a unitary transformation. What is this unitary transformation?

**Comment by susilehtola** [comment]
Are you talking about the atomic orbital (AO) representation? That is wholly dependent on the way you define the basis functions, and things like shell ordering, basis function normalization, and phase will show up in the AO Fock matrices. The transformation is not necessarily unitary.

**Comment by thu-wangz17** [comment]
Thank you for the answer. Yes, the Hamiltonian is expressed under atomic orbital representation. I guess the basis functions are defined differently in pyscf and psi4. For example, $m=0, +1, -1, +2, -2$ in psi4 but $m=-l, \cdots, 0, \cdots, l$ in pyscf. But with this permtation, these two Hamiltonians are still different. I want to convert Hamiltonian from pyscf into that from psi4. Could you give me some suggestions.

**Comment by thu-wangz17** [comment]
I have a matrix calculated from psi4 and a Hamiltonian calculated from pyscf. I want to calculate their Hadamard product, but I find the AOs are different between psi4 and pyscf. So I want to convert Hamiltonian from pyscf to psi4 to make AOs of these two matrices be the same.

**Comment by 1234zou** [comment]
Hi, what does "Hamiltonian" mean here?

In theoretical chemistry, people often use specific words like Fock matrix, molecular orbital coefficients, CI Hamiltonian matrix, AO-based two-electron integrals,  MO-based two-electron integrals, etc. When we see these words, we know exactly what it is. But in some other fields, people use fuzzy/ambiguous words, especially the word "Hamiltonian" which could be anything (and this is terrible in a discussion). So, telling us its specific meaning will do some help. If it means Fock matrix, better tell us whether it is AO-based Fock matrix or MO-based Fock matrix.

By the way, usually you cannot multiply a matrix from program A by another matrix from program B, especially for AO-based quantities. This is because a basis set name "def2-SVP" or "cc-pVDZ" may have different basis set data in different programs. So [MOKIT](https://gitlab.com/jxzou/mokit) will firstly transfer basis set data between programs, and then deal with the permutations (and multiplication of some constants) of MO coefficients. But for MO-based quantities, it is possible to do that, which depends on the specific quantity.

**Comment by verena-neufeld** [comment]
Hi @thu-wangz17 , thanks! Has your question been answered or should this issue stay open?

**Comment by sunqm** [comment]
Saving the integrals in an intermediate data format like TREXIO can solve the issue. The interface to TREXIO will be implemented in pyscf in the future.

Please feel free to reopen the issue to continue the discussion.
