### ISSUE TITLE
PBE not converged for (NH3)2+

### ISSUE THREAD

**Issue by lzx0106** [pyscf/pyscf#2129]
Dear developers,

I've been trying to get pbe energy of (NH3)2+ by

```

mol = gto.Mole()
mol.build(
    atom = [("N", (-0.27798285, -0.27798285, -0.57712274)), ("H", (-0.74557194, -1.08787091, -0.19166343)),
    ("H", (-0.74557194, 0.53190521, -0.19166343)), ("H", (0.65719533, -0.27798285, -0.19166343)),
    ("N", (8.27798285, 8.27798285, 8.28802826)), ("H", (8.78738295, 7.39567599, 8.28802826)),
    ("H", (8.78738295, 9.16028971, 8.28802826)), ("H", (7.25918264, 8.27798285, 8.28802826))],
    basis="aug-ccpvtz",
    unit='Angstrom',
    charge = 1,
    spin=1,
)
uks = scf.UKS(mol)
uks.xc = 'pbe'
uks.max_cycle = 120
uks.kernel()

```
but it doesn't converge, I've also tried different initial guesses and 'uks.level_shift = 0.2' but I can still not make it converge. Could you please tell me a method to make it converge?

**Comment by xubwa** [comment]
Have a look at this. You may also second-order scf which is usually pretty robust. https://pyscf.org/user/scf.html#converging-scf-iterations   From: lzx0106Sent: Tuesday, March 12, 2024 8:36 AMTo: pyscf/pyscfCc: SubscribedSubject: [pyscf/pyscf] PBE not converged for (NH3)2+ (Issue #2129) Dear developers,I've been trying to get pbe energy of (NH3)2+ by mol = gto.Mole()mol.build(    atom = [("N", (-0.27798285, -0.27798285, -0.57712274)), ("H", (-0.74557194, -1.08787091, -0.19166343)),    ("H", (-0.74557194, 0.53190521, -0.19166343)), ("H", (0.65719533, -0.27798285, -0.19166343)),    ("N", (8.27798285, 8.27798285, 8.28802826)), ("H", (8.78738295, 7.39567599, 8.28802826)),    ("H", (8.78738295, 9.16028971, 8.28802826)), ("H", (7.25918264, 8.27798285, 8.28802826))],    basis="aug-ccpvtz",    unit='Angstrom',    charge = 1,    spin=1,)uks = scf.UKS(mol)uks.xc = 'pbe'uks.max_cycle = 120uks.kernel() but it doesn't converge, I've also tried different initial guesses and 'uks.level_shift = 0.2' but I can still not make it converge. Could you please tell me a method to make it converge?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by 1234zou** [comment]
This system is intrinsically multiconfigurational. It requires two Slater determinants (with spin doublet) at least. The unpaired electron can either be located on one NH3, or on another NH3. The regular SCF is very difficult  to be converged since beta HOMO and beta LUMO are degenerate in the UPBE/aug-cc-pVTZ level. And there exists multiple UPBE solutions. That is to say, even if you obtain a converged solution by accident, it may not be the lowest one. It would be better to use the CASSCF method to study this system.

Although it is very difficult, the UDFT SCF can be converged, especially if using a good initial guess or a second-order SCF solver. Qiming wrote [an excellent tutorial](https://mp.weixin.qq.com/s/80ROWGjZJgrQo5yXQVgKCg) in Chinese, about SCF convergence techniques in PySCF. I'm sure that you can solve the convergence issue after reading the tutorial. Of course, PySCF manual/documentation can help you, too.

Here I want to say something different. If you simply use a second-order SCF solver, e.g.
```
mf2 = dft.UKS(mol)
mf2.xc = 'pbe,pbe'
mf2.grids.atom_grid = (99,590) # eqv. int=ultrafine in Gaussian
mf2.verbose = 4
mf2.max_memory = 64000 #MB
mf2 = mf2.newton()
mf2.kernel()
mf2.stability()
```
you will probably obtain E(UPBE) = -112.646625 a.u. This wave function is stable, but it is not the lowest one. The lowest UPBE energy is -112.707868 a.u. (which I can find so far). Here is how I perform the calculation:

**(1) perform the UPBE calculation using Gaussian**
Here is the test.gjf file
```
%chk=test.chk
%mem=10GB
%nprocshared=8
#p UPBEPBE/aug-cc-pVTZ nosymm int=nobasistransform scf(xqc,maxcycle=128) stable=opt

title

1 2
N  -0.27798285, -0.27798285, -0.57712274
H  -0.74557194, -1.08787091, -0.19166343
H  -0.74557194, 0.53190521, -0.19166343
H   0.65719533, -0.27798285, -0.19166343
N   8.27798285, 8.27798285, 8.28802826
H   8.78738295, 7.39567599, 8.28802826
H   8.78738295, 9.16028971, 8.28802826
H   7.25918264, 8.27798285, 8.28802826

```
After the Gaussian job is accomplished, we obtain E(UPBE) = -112.707836 a.u.

**(2) transfer MOs from Gaussian to PySCF**
Here is the Python script
```
from pyscf import dft, lib
from mokit.lib.gaussian import load_mol_from_fch, mo_fch2py

lib.num_threads(64)
hf_fch = 'test.fch'
mol = load_mol_from_fch(hf_fch)
mo = mo_fch2py(hf_fch)

mf = dft.UKS(mol)
mf.xc = 'pbe,pbe'
mf.grids.atom_grid = (99,590)
mf.max_cycle = 1
mf.max_memory = 64000 #MB
mf.kernel()

mf.conv_check = False
mf.level_shift = 0.1
mf.max_cycle = 50
mf.mo_coeff = mo
dm = mf.make_rdm1()
mf.kernel(dm0=dm)
mf.stability()
```
You can find that SCF is converged immediately
```
init E= -112.707867547256
  alpha nocc = 10  HOMO = -0.44745004352223  LUMO = -0.0633739282620982
  beta  nocc = 9  HOMO = -0.403236984406229  LUMO = -0.303236983821606
cycle= 1 E= -112.707867510111  delta_E= 3.71e-08  |g|= 1.14e-06  |ddm|= 3.98e-06
  alpha nocc = 10  HOMO = -0.447449700577495  LUMO = -0.0633738618156422
  beta  nocc = 9  HOMO = -0.403236642013304  LUMO = -0.303236640741708
cycle= 2 E= -112.707867510111  delta_E= 1.14e-13  |g|= 1.25e-06  |ddm|= 8.42e-07
converged SCF energy = -112.707867510111  <S^2> = 0.75297956  2S+1 = 2.0029773
<class 'pyscf.dft.uks.UKS'> wavefunction is stable in the internal stability analysis
```
Here the extra iteration is turned off (`mf.conv_check = False`) since it will change the converged SCF orbitals to unconverged orbitals (which is possibly due to the energy degeneracy between beta HOMO and beta LUMO).

It is possible that you can obtain these two SCF energies using other tricks by trial and error. But what I show is supposed to be the briefest. Have fun with tricks.

**Comment by susilehtola** [comment]
Yes, the issue with the system is that you are studying the cation of a molecular complex at large separation, and you basically need to use direct minimization to make this converge.

Since you know that the molecules are far away, you can set up a molecular guess that should get you close to the solution.

```
import pyscf

# First molecule in full basis, neutral
mol1n = pyscf.M(
    atom = '''
N -0.27798285 -0.27798285 -0.57712274
H -0.74557194 -1.08787091 -0.19166343
H -0.74557194 0.53190521 -0.19166343
H 0.65719533 -0.27798285 -0.19166343
ghost-N 8.27798285 8.27798285 8.28802826
ghost-H 8.78738295 7.39567599 8.28802826
ghost-H 8.78738295 9.16028971 8.28802826
ghost-H 7.25918264 8.27798285 8.28802826
''',
    basis = 'ccpvdz',
    symmetry = True,
)

# First molecule in full basis, cation
mol1c = pyscf.M(
    atom = '''
N -0.27798285 -0.27798285 -0.57712274
H -0.74557194 -1.08787091 -0.19166343
H -0.74557194 0.53190521 -0.19166343
H 0.65719533 -0.27798285 -0.19166343
ghost-N 8.27798285 8.27798285 8.28802826
ghost-H 8.78738295 7.39567599 8.28802826
ghost-H 8.78738295 9.16028971 8.28802826
ghost-H 7.25918264 8.27798285 8.28802826
''',
    basis = 'ccpvdz',
    symmetry = True,
    charge = 1,
    spin = 1
)

# Second molecule in full basis, neutral
mol2n = pyscf.M(
    atom = '''
ghost-N -0.27798285 -0.27798285 -0.57712274
ghost-H -0.74557194 -1.08787091 -0.19166343
ghost-H -0.74557194 0.53190521 -0.19166343
ghost-H 0.65719533 -0.27798285 -0.19166343
N 8.27798285 8.27798285 8.28802826
H 8.78738295 7.39567599 8.28802826
H 8.78738295 9.16028971 8.28802826
H 7.25918264 8.27798285 8.28802826
''',
    basis = 'ccpvdz',
    symmetry = True,
)

# Second molecule in full basis, cation
mol2c = pyscf.M(
    atom = '''
ghost-N -0.27798285 -0.27798285 -0.57712274
ghost-H -0.74557194 -1.08787091 -0.19166343
ghost-H -0.74557194 0.53190521 -0.19166343
ghost-H 0.65719533 -0.27798285 -0.19166343
N 8.27798285 8.27798285 8.28802826
H 8.78738295 7.39567599 8.28802826
H 8.78738295 9.16028971 8.28802826
H 7.25918264 8.27798285 8.28802826
''',
    basis = 'ccpvdz',
    symmetry = True,
    charge = 1,
    spin = 1
)

# Run molecular calculations
mol1nks = mol1n.UKS()
mol1nks.xc = 'PBE'
mol1nks.kernel()

mol1cks = mol1c.UKS()
mol1cks.xc = 'PBE'
mol1cks.kernel()

mol2nks = mol2n.UKS()
mol2nks.xc = 'PBE'
mol2nks.kernel()

mol2cks = mol2c.UKS()
mol2cks.xc = 'PBE'
mol2cks.kernel()

# Molecular calculation
mol = pyscf.M(
    atom = '''
N -0.27798285 -0.27798285 -0.57712274
H -0.74557194 -1.08787091 -0.19166343
H -0.74557194 0.53190521 -0.19166343
H 0.65719533 -0.27798285 -0.19166343
N 8.27798285 8.27798285 8.28802826
H 8.78738295 7.39567599 8.28802826
H 8.78738295 9.16028971 8.28802826
H 7.25918264 8.27798285 8.28802826
''',
    basis = 'ccpvdz',
    symmetry = True,
    charge = 1,
    spin = 1,
    verbose = 5
)
molks = mol.UKS().newton()
molks.xc = 'PBE'

# Test guess 1: mol 1 neutral, mol 2 cation
dm_1n = mol1nks.make_rdm1()
dm_1c = mol1cks.make_rdm1()
# Test guess 2: mol 1 cation, mol 2 neutral
dm_2n = mol2nks.make_rdm1()
dm_2c = mol2cks.make_rdm1()

# Density matrices
dm_1n2c = [dm_1n[i]+dm_2c[i] for i in range(2)]
dm_1c2n = [dm_1c[i]+dm_2n[i] for i in range(2)]

# Evaluate guess energies
E_1n2c = molks.energy_tot(dm=dm_1n2c)
print(f'{E_1n2c=}')
E_1c2n = molks.energy_tot(dm=dm_1c2n)
print(f'{E_1c2n=}')

# Run calculation with lower state
if E_1n2c < E_1c2n:
    molks.kernel(dm0 = dm_1n2c)
else:
    molks.kernel(dm0 = dm_1c2n)
```

**Comment by 1234zou** [comment]
Hi, prefessor @susilehtola , thank you for you detailed explaination. It seems that you are using `cc-pVDZ` and thus its electronic energy cannot be compared to that of `aug-cc-pVTZ`.

I also tried two different fragment schemes in Gaussian and use the combination of fragment orbitals as the initial SCF guess. I found that they all led to the same result (E(UPBE) = -112.707836 a.u.) finally, so I only show one Gaussian input file.

**Comment by susilehtola** [comment]
@1234zou total energies in different basis sets *can* be compared, since even density functional energies are variational with respect to the basis set. However, you are right, your aug-cc-pVTZ numbers were actually clearly lower than my cc-pVDZ values. I might have switched to a smaller basis set to debug the script.

Note that Gaussian does not use the same definition of PBE; you need to use `mf.xc = 'gga_x_pbe_gaussian,gga_c_pbe_gaussian` to get energies that can be compared to Gaussian; see our recent work in [J. Chem. Phys. 159, 114116 (2023)](https://doi.org/10.1063/5.0167763).

Rerunning the script with the correct basis set and exchange-correlation functional I get three results:
```
converged SCF energy = -111.789111173238  <S^2> = 0.80670991  2S+1 = 2.0559279
converged SCF energy = -111.617814134744  <S^2> = 1.7546252  2S+1 = 2.8316957
converged SCF energy = -111.822864420505  <S^2> = 0.75253111  2S+1 = 2.0025295
```
the first corresponding to mol 1 neutral mol 2 cation, the second to mol 1 cation mol 2 neutral, and the third one to the default guess.

**Comment by verena-neufeld** [comment]
Hi @lzx0106 , thanks! Has your question been answered or should this issue stay open?

**Comment by sunqm** [comment]
I'll close this issue since the responses clearly explain the problem. Please feel free to reopen this issue if you have more questions.
