### ISSUE TITLE
##

### ISSUE THREAD

**Issue by gchirchir** [pyscf/pyscf#2133]
Dear Colleagues,

I have performed overlap calculations of the Helium atom using the aug-cc-pvqz basis set with my own developed code. Upon comparison with data generated by Pyscf, I have observed that the results correspond well for the S and P shells. However, there are discrepancies in the data for the D and F shells.

I believe that achieving full normalization of the D, F, G, and higher shells in the Pyscf code will enable better alignment with the results obtained from my code. I believe that the by knowing how   D, F, G, and higher shells  normalization are done will ensure that the data from both sources are consistent and comparable.

I have attached a .csv file named "He_aug-cc-pvqz_Pyscf_mycode_dat.csv", which contains the comparison of the data obtained from my code and Pyscf. I hope that by addressing the normalization issue, I  can achieve better agreement between the results.

Best regards,
[Gabriel chirchir]
[He_aug-cc-pvqz_Pyscf_mycode_dat .csv](https://github.com/pyscf/pyscf/files/14613506/He_aug-cc-pvqz_Pyscf_mycode_dat.csv)

**Comment by sunqm** [comment]
D, F, G are not normalized, due to the historical reasons in the underlying integral library. You will have to compute the diagonal elements of overlap matrix and normalize the corresponding functions.

For some basis functions, such as xx, yy, zz, xxx, yyy, zzz, ... you can multiply ((2l+1)/(4*pi))**.5 to normalize the Pyscf basis functions. There is no such relations for the other functions. You will have to manually align the results.

**Comment by gchirchir** [comment]
Thank very much for this great insight

**Comment by sunqm** [comment]
If you have more questions, feel free to reopen the issue to continue the discussion.
