### ISSUE TITLE
cart2sph Question

### ISSUE THREAD

**Issue by jstoppelman** [pyscf/pyscf#2166]
Hello, I had a question about `gto.mole.cart2sph`.  I get back the same (6, 5) transformation matrix for the d orbitals, no matter which option I use for the 'normalized' argument: 

```
gto.mole.cart2sph(2, normalized='sp')

gto.mole.cart2sph(2, normalized='all')

gto.mole.cart2sph(2, normalized='none')
```
My thought was, if I entered `normalized='all'`, then I would get a similar matrix for converting the cartesian d orbitals to spherical as you would see in Wikipedia or a textbook. I printed out what I expected to see below, in fractional form so it's clear what I'm referring to:
```
#xx   [[0.0          0.0        -1/2       0.0           sqrt(3)/2     ]
#xy    [sqrt(3)      0.0         0.0       0.0           0.0           ]
#xz    [0.0          0.0         0.0       sqrt(3)       0.0           ]
#yy    [0.0          0.0        -1/2       0.0          -sqrt(3)/2     ]
#yz    [0.0          sqrt(3)     0.0       0.0           0.0           ]
#zz    [0.0          0.0         1.0       0.0           0.0           ]]
   ````
Or am I misunderstanding the purpose of this function?

**Comment by tberkel** [comment]
You can look at the function and its docstring [here](https://github.com/pyscf/pyscf/blob/master/pyscf/gto/mole.py#L153). The only kwarg that `normalized` respects is `normalized='sp'`, which triggers whether the s and p functions are normalized, due to a convention of the libcint integral library used by pyscf (and the d orbitals are not normalized). However, you can get the matrix you want by normalizing by hand via `gto.mole.cart2sph(2)/0.630783130505`.

**Comment by jstoppelman** [comment]
Ok thanks, this can be closed now.
