### ISSUE TITLE
How to explain values of Hartree-Fock 2RDM

### ISSUE THREAD

**Issue by neutronengas** [pyscf/pyscf#2182]
I calculated the 2-Reduced Density Matrix for Hartree Fock which takes the form (in the MO basis) of 

dm2[i,i,i,i] = 2
dm2[i,j,j,i] = -2
dm2[i,i,j,j] = 4
otherwise = 0

I currently do not see how these values come to be - i.e. I don't see what the formula is that calculates dm2

**Comment by jamesETsmith** [comment]
@neutronengas could you share a minimal working example for your problem? Are you confused by the values themselves or how PySCF calculated them?

For reference, here's a screenshot of [Helgaker's Molecular Electronic Structure Theory ](https://www.wiley.com/en-us/Molecular+Electronic+Structure+Theory-p-9781118531471) outlining several properties of the 1-/2-RDM. Equation 10.4.18 and 10.4.19 should give you everything you need:

![image](https://github.com/pyscf/pyscf/assets/11277676/f98479da-e68b-4eaa-82be-46da62a1b83f)

**Comment by tberkel** [comment]
And note that these are spin-summed density matrices, which is why you can have values like 2 and 4, instead of just 0 or 1.

**Comment by tberkel** [comment]
That equality is because Hartree-Fock is a mean-field theory, so its 2RDM factorizes into products of 1RDMs. In other words, the HF wavefunction is just a single determinant, for which this is equality holds.

For general quantum chemistry questions that are not specifically about PySCF, please consult a textbook or ask on a more appropriate forum, like the [Matter Modeling StackExchange](https://mattermodeling.stackexchange.com/).

**Comment by neutronengas** [comment]
I See, thank you very much!
