### ISSUE TITLE
Interface to the PyFraME package for Polarizable Embedding

### ISSUE THREAD

**Issue by JonasProg** [pyscf/pyscf#2214]
Hi,

I would like to write an interface in PySCF to the PyFraME package for embedding calculations starting with polarizable embedding QM/MM. I want to enable SCF and geometry optimizations with PE (and possibly Hessian calculations).

Regarding the gradients necessary for the geometry optimizations (and second-order derivatives for the Hessian), I would like to
 know which intor to use to get geometric derivatives of the following one-electron electrostatic-potential integral and its potential derivatives:

```math
t^{[\alpha]}_{\mu\nu} = \int \chi_\mu(r; R_n) T^{[\alpha]}(R_s, r) \chi_\nu(r; R_n) dr
```
where 
```math
T^{[\alpha]}(R_s, r) = \partial^{\alpha}_{r} \frac{1}{|r - R_s|}
```
Here $R_s$ is the position of a MM site, $R_n$ is the nuclear position, and $\alpha$ is a multi-index associated with the three cartesian coordinates. 

The method is described in: https://doi.org/10.1021/acs.jctc.0c01323

**Comment by sunqm** [comment]
I think this functionality fits well in https://github.com/pyscf/pyscf-forge . In the future, new features will be first made available in pyscf-forge . This process is supposed to be quick, without too many restrictions. Once they are stable in forge, we can engage the transition from pyscf-forge repo to the pyscf repo.

**Comment by maxscheurer** [comment]
Some hints on the integrals (without derivatives) can be found in the existing PE implementation in `pyscf` [here](https://github.com/pyscf/pyscf/blob/master/pyscf/solvent/pol_embed.py).
I had a working PE-SCF gradients implementation in [this](https://github.com/maxscheurer/pyscf/blob/pe_gradients/pyscf/solvent/pol_embed_grad.py) branch from years ago, but haven't touched it since... Hope this helps!

**Comment by JonasProg** [comment]
I've opened a new issue on pyscf-forge. Thank you very much @maxscheurer it was very helpful!
