### ISSUE TITLE
CASCI in PBC system 

### ISSUE THREAD

**Issue by emamars95** [pyscf/pyscf#2219]
Dear, 

I have one quick question regarding the possibilities of running a CASCI (and/or CASSCF) calculation on top on a PBC.SCF object.

Reading the manual and the code implementation of the CASCI routine it looks to me that it should be possible since the required electronic integrals are read from a PBC SCF calculation. However, after performing the calculation I noticed that the CASCI energy is higher that the underlined HF calculation. This, of course, it is no sense. 

Am I missing something obvious here?

**Comment by emamars95** [comment]
I see. Thanks @tberkel! I would be happy if you can also address the following two questions:  
1) I guess it should not but setting the exxdiv=None can give problems in the SCF convergence? 
2) Is there any reason why, in post-HF calculation, the integrals are set to zero for vanishing wave vector and not treated as in HF?

**Comment by tberkel** [comment]
1. Yes it could in principle give SCF problems, because the Madelung
constant acts like a level shift. You can use a level shift if you have SCF
convergence problems.

2. It’s a bit complicated. Even in HF, you can’t uniquely correct the
“integrals”, because Coulomb and exchange are treated differently.
Neglecting the contribution from G=0 in all integrals is equivalent to
using the Ewald potential in place of the Coulomb potential. Associating
the Madelung constant with the exchange energy in HF is thus somewhat
arbitrary, but a common convention.
