### ISSUE TITLE
CCSD molden file making

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2225]
Hello! Thanks for wonderful works!

I want to make a CCSD calculation's molden file.

I looked at  example/tools/02-molden.py, but it only had an example for RHF. 

I wonder if there are any changes I need to make to make it work for CCSD.

Thank you!

**Comment by tberkel** [comment]
Which part of a molden file are you interested in? CCSD does not produce
MOs or MO energies, and a typical ("unrelaxed") calculation does not update
the electron density.

**Comment by sehun1618** [comment]
I'm trying to plot localized orbital locator (LOL) by using Multiwfn.

Asked because only files in .wfn or .molden format are possible.

**Comment by tberkel** [comment]
The calculation of the relaxed CCSD density matrix is not supported. You can investigate the HF density matrix if you want. Or, the relaxed CCSD density matrix can be calculated by hacking together your own code based on the `_response_dm1` function the [CC gradient code](https://github.com/pyscf/pyscf/blob/master/pyscf/grad/ccsd.py#L267).

**Comment by sunqm** [comment]
If you mean to dump the natural orbital, you can compute it using code like the following. Then dumping it to molden format using the  method in example 02-molden.py
```
dm = cc.make_rdm1()
e, v = np.linalg.eigh(dm)
natocc = e[::-1]
natorb = cc.mo_coeff.dot(v[:,::-1])
```

**Comment by tberkel** [comment]
Yes, sorry, I was perhaps a bit sloppy with my language. To be more clear:
- The eigenvectors of the HF density matrix are the molecular orbitals.
- The CCSD density matrix that is relaxed _with respect to the CC amplitudes_ can be calculated with `cc.make_rdm1()`, as @sunqm said. This will be different than the HF density matrix, and its eigenvectors are commonly called natural orbitals. The occ-vir block of this density matrix is zero. Calculating this density matrix requires solving the Lambda equations, which is a step beyond a usual CC calculation. 
- The occ-vir contribution to the CC density matrix is due to orbital relaxation, and calculating this contribution can be done by following the CC gradient code.

Depending on your goals, the "unrelaxed" density matrix obtained with `cc.make_rdm1()` is perhaps sufficient. See also `examples/cc/01-density_matrix.py`

**Comment by sehun1618** [comment]
Sorry for bothering and thanks to detailed explanation.

 So, as @sunqm said, "natocc" is corresponding to mf.mo_energy & "natorb" is corresponding to mf.mo_coeff?

**Comment by verena-neufeld** [comment]
Hi @sehun1618 , thanks for your questions. `natocc` corresponds to the eigenvalues of the unrelaxed CCSD density matrix (not the mf.mo_energy) and `natorb` to the natural CC orbitals, not the molecular coefficients (mf.mo_coeff).
