### ISSUE TITLE
NACs (and forces) for SS-CASSCF

### ISSUE THREAD

**Issue by ghb24** [pyscf/pyscf#2284]
We are interested in obtaining NACs and forces for a set of SS-CASSCF states. 

@matthew-hennefarth and @MatthewRHermes, I know you have recently implemented this in pyscf for SA-CASSCF (many thanks!), but I just wanted to get your thoughts on whether you think this can be straightforwardly hacked for the equivalent quantities for given SS-CASSCF states? Any advice on this (or where it might fall down) before embarking on this ourselves would be very much appreciated.

**Comment by matthew-hennefarth** [comment]
I have 3 comments:

1. Your MOs are no longer going to be orthonormal to one another. So when you get the transition density matrix elements, you will have to consider the entire orbital space since inactive, active, and virtual subspaces likely won't coincide with one another. Make sure to use the overlap matrix appropriately. Also, you will have to consider elsewhere in the derivation/equations where the assumption that orthonormal MOs is used. As far as I am aware, though, PySCF doesn't have a function to compute these TDM between states of different orbitals (but I may be wrong!).
2. I have a feeling that the standard derivation for SA-CASSCF NACs requires that the 2 states of interest are eigenstates of the projected model-space Hamiltonian. You will have to rationalize from the beginning what exactly the derivation should be and see if the equations align.
3. Along with point 2 above, SA-CASSCF states are *not* variational. Hence, one uses a Lagrangian technique to achieve derivatives. SS-CASSCF states are variational and hence one doesn't need to use Lagrangian techniques to achieve derivatives. I am not sure about NACs if one can get away with not using the Lagrangian method, so care should be taken here.

**Comment by MatthewRHermes** [comment]
I have the strange feeling like I've seen SS-CASSCF NACs before, but I can't find the article. Anyway based on my playing in my notebook for about an hour, you're going to want to take a right turn in the derivation pretty quickly because of @matthew-hennefarth's point 2 above. In SA-CASSCF, the chain-rule term involving the derivative of the CI eigenvectors is obtained by differentiating both sides of the CASCI active-space-projected Schrödinger equation and rearranging. However, this involves a resolution of the identity over a complete CASCI eigenstate basis. This is OK for SA-CASSCF because the bra is itself a CASCI eigenstate in the same orbitals, which contributes a delta function so you end up with a nice, simple expression involving the derivative of the Hamiltonian element between the two states. But this does not happen so cleanly if your bra is defined in a different set of orbitals. You would end up having to _invert the entire active-space Hamiltonian matrix_, which would only be practical for very small active spaces.

However, you can always change strategies and use Lagrange multipliers instead. Define 

$$
\langle\tilde{\Psi}_J|\frac{d}{d\lambda}\Psi_I\rangle \equiv \frac{d}{d\lambda}\mathcal{F}
$$

and then

$$
\mathcal{L}\equiv\mathcal{F}+\nabla_{\textrm{orb}} E_{\textrm{CAS}}\cdot\vec{\kappa}+\nabla_{\textrm{CI}} E_{\textrm{CAS}}\cdot\vec{P}
$$

Differentiating this with respect to orbital and CI rotations again gives the usual CASSCF Hessian on the right-hand side, plus driving terms (`wfn_response` in the nomenclature of the SA-CASSCF NACs implementation). The driving terms work out to 1-body transition density matrices and the projection of the bra into the basis of the ket's active-space determinants.

So overall, I'd say you can probably reuse some of the structure, but you have to rederive the content of the individual functions, as well as implement some new (to PySCF) technology for transition density matrices and overlaps involving different orbital bases.

**Comment by ghb24** [comment]
Many thanks both for your thoughts here - very helpful. We already have code for computing transition 1 and 2-body DMs between these states, so think that if we get the derivation right and can plug into the right pyscf functionality this shouldn't be too painful. Really appreciate you taking the time.

I'll close this issue, since it has turned into a theory rather than pyscf chat, and I'll perhaps reach out to you through a different channel to discuss further.
