### ISSUE TITLE
scf.mol.nao_nr() gives incorrect result after loading from fcidump

### ISSUE THREAD

**Issue by kevinsung** [pyscf/pyscf#2303]
The function `pyscf.tools.fcidump.to_scf` doesn't properly set the molecule's number of orbitals.

```python
import pyscf
import pyscf.tools

# Build molecule
mol = pyscf.gto.Mole()
mol.build(
    atom=[["H", (0, 0, 0)], ["H", (1.0, 0, 0)]],
    basis="sto-6g",
    symmetry="Dooh",
    verbose=0,
)

# Run SCF
scf = pyscf.scf.RHF(mol).run()

# nao and nao_nr() give same result
print(f"nao before: {scf.mol.nao}")
print(f"nao_nr() before: {scf.mol.nao_nr()}")
assert scf.mol.nao == scf.mol.nao_nr()

# Save to FCIDUMP and load it back
pyscf.tools.fcidump.from_scf(scf, "test.fcidump")
scf = pyscf.tools.fcidump.to_scf("test.fcidump")

# nao and nao_nr() give different results
print(f"nao after: {scf.mol.nao}")
print(f"nao_nr() after: {scf.mol.nao_nr()}")
assert scf.mol.nao == scf.mol.nao_nr()
```
```
nao before: 2
nao_nr() before: 2
Parsing test.fcidump
nao after: 2
nao_nr() after: 0
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[1], [line 28](vscode-notebook-cell:?execution_count=1&line=28)
     [26](vscode-notebook-cell:?execution_count=1&line=26) print(f"nao after: {scf.mol.nao}")
     [27](vscode-notebook-cell:?execution_count=1&line=27) print(f"nao_nr() after: {scf.mol.nao_nr()}")
---> [28](vscode-notebook-cell:?execution_count=1&line=28) assert scf.mol.nao == scf.mol.nao_nr()

AssertionError:
```

**Comment by sunqm** [comment]
The `mol.nao_nr` method computes the number of basis functions based on the atoms, basis sets in the molecule. `mol.nao` is an attribute that allows overwritten. When mol is loaded from `FCIDUMP` , number of basis functions are read from the FCIDUMP file, but the geometry of the molecule is missing.

I tend to not change the output of `nao_nr`. Because it is supposed to be consistent with a bunch of other functions that produces GTO basis locations, such as `ao_loc_nr`, `nao_cart`, `nao_2c` (= 2*nao_nr()).

**Comment by kevinsung** [comment]
I see. I still find this behavior to be confusing, but I'm not sure if there's a good way to fix it. Perhaps it's just a matter of documenting more clearly the difference between `nao_nr` and `nao`. Feel free to close this issue if there's nothing to be done.
