### ISSUE TITLE
TMP File Too Large in Two-Electron Calculation

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#2321]
Dear PySCF Community,

I am encountering an issue with the calculations of two-electron integrals using the "r_outcore" module, which generates temporary files that are too large for regular disks. For instance, in an H2S molecule with a cc-pVTZ basis set, the H5 file with the integrals is 58 MB, but the temporary file used during the calculation is 250 MB.

```
from pyscf import gto, scf
import numpy as np
from pyscf.ao2mo import r_outcore

mol = gto.M(atom="""H1 0 2 0; H2 0 0 0; S 0 1 0""", 
                    basis="cc-pvtz", unit="angstrom")

mf = scf.dhf.DHF(mol).run()

mo_coeff = mf.mo_coeff
mo_occ = mf.mo_occ
n4c, nmo = mo_coeff.shape
n2c = nmo // 2
occidx = np.where(mo_occ == 1)[0]
viridx = n2c + np.where(mo_occ[n2c :] == 0)[0]
orbv = mo_coeff[:, viridx]
orbo = mo_coeff[:, occidx]
nvir = orbv.shape[1]
nocc = orbo.shape[1]
mo = np.hstack((orbo, orbv))

moL = np.asarray(mo[:n2c, :], order="F")
orboL = moL[:, : nocc]
orbvL = moL[:, nocc :]
erifile = 'eri.h5'
r_outcore.general(
    mol, (orboL, orbvL, orbvL, orboL), erifile, dataname='A1', intor="int2e_spinor", verbose=5
, max_memory=3000, ioblk_size=5000)
```

I am planning to run these calculations on larger systems. Is there a way to limit the size of the temporary file?

Best regards,
Daniel

**Comment by sunqm** [comment]
Did you try setting the `TMPDIR` environment variable?

The intermediate is a partially transformed integral, with complex type, sized as `(nocc, nvir, nao, nao)` . In this system, nocc = 18, nvir = 106, nao = 124 .  The size of intermediates cannot be reduced, unless you transform the orbitals to scalar basis, using the `mol.sph2spinor_coeff()`, then calling the non-relativistic integral transformation. I'd recommend to run the calculation using a large disk than writing the the non-relativistic integral transformation code.

**Comment by xubwa** [comment]
The nrr_outcore function for integral transformation is doing the transformation as @sunqm described, but I've only used it to handle int2e_spinor. In this issue, since a 4c calculation is mentioned, one would also need to transform the llss and ssss integrals. Doing it in scalar basis is more complicated and needs to be carried out with care. The save in disk space is only 4-fold, since instead of having a tmpfile of size (nocc, nvir, nao_2c, nao_2c), this time you will have a tmpfile of size (nocc, nvir, nao_nr, nao_nr). I'd recommend similar to Qiming that having a larger disk might be easier for integral transformation purpose.

**Comment by DanielBajac** [comment]
Thank you very much for your response and recommendations!
