### ISSUE TITLE
Difference between GAMESS and PySCF CASCI configuration count

### ISSUE THREAD

**Issue by NastaMauger** [pyscf/pyscf#2422]
Hello,

I am performing a CASCI calculation with PySCF and am comparing the results to those obtained from GAMESS using the GUGA method. Although both software yield the same energy, I noticed a discrepancy in the number of configurations reported.
GAMESS shows in its input before CI matrix diagonalization: `COMPUTING THE HAMILTONIAN FOR THE 2210880 CSF-S...`
However, in my PySCF script, the following code:
```
all_configs = cistring.make_strings(range(norb), nelec)
print(f'Number of configurations: {len(all_configs)}')
```
outputs 19,448 configurations.
Both codes use the same number of electrons and active orbitals, so I am puzzled by the difference. Both code also run in the D2 group and CI wfn symmetry A.

Here my input: [input_git.txt](https://github.com/user-attachments/files/17022921/input_git.txt)

However, using FCI solver with PySCF and ALDET algorithm with GAMESS give exactly the same number of determinants (and also lead to the same energy). So, it is relates to the CASCI configuration generation I guess

Any insights would be greatly appreciated.

**Comment by JangidBhavnesh** [comment]
In the first instance, you are comparing the number of CSFs (Configuration State Functions) to the number of determinants; these are two different bases used to solve the FCI.

#CSFs <= #Determinants

In the second case, you obtained the same number of configurations because you were comparing like for like.

Now, if you want to use the CSF basis in PySCF, you would need the MRH package (https://github.com/MatthewRHermes/mrh), and you can set your input as follows

from mrh.my_pyscf.fci import csf_solver
mc = mcscf.CASCI(mf, ncas, nelecas)
mc.fcisolver = csf_solver(mol, smult=1)

For more info, have a look at #1805

**Comment by NastaMauger** [comment]
Thank you so much for your help and for letting me know about the MRH package. It is greatly appreciated!
