### ISSUE TITLE
CASSCF Convergence Issue

### ISSUE THREAD

**Issue by joshz793** [pyscf/pyscf#2493]
I'm performing a CASSCF calculation with a Mn atom (6o, 7e) at high spin state (S^2 = 8.75) using csf_solver as the fcisolver.

The output file is attached, the system no longer appears to change after 18 macro cycles, yet is not converged after 150 macro cycles.

[out.txt](https://github.com/user-attachments/files/17579420/out.txt)

**Comment by susilehtola** [comment]
The input is missing

**Comment by joshz793** [comment]
Apologies, please see [input.txt](https://github.com/user-attachments/files/17595579/input.txt).

The original output file was truncated from a series of calculations; the following output is the problematic(?) system alone.
[out.txt](https://github.com/user-attachments/files/17595580/out.txt)

**Comment by matthew-hennefarth** [comment]
Small note:
```python3
solver = csf_solver(mol, smult=6)
solver.spin=5
```
I would set `smult` appropriately and not bother changing `spin`. This won't affect your final convergence though.

I have run into this problem before and I believe it is a bug in the `csf_solver` due to the stepsize going to zero before convergence is reached. You can see in your output that `|maxRot[o]| = 0.0000` eventually, meaning that it cannot take any step (despite not reaching convergence). @MatthewRHermes would know better how to solve this.

**Comment by MatthewRHermes** [comment]
With that spin, in that active space, the wave function is _effectively_ single-determinantal - there are multiple configurations, but they're all expressible as |211111> after an orbital rotation. The csf_solver is actually unnecessary here, because spin contamination is impossible.

There may be some subtle interaction here between csf_solver and the mcscf kernel that's undesirable. But the real underlying problem is that one active orbital is 100% occupied, so the energy is 100% insensitive with respect to rotation between that active orbital and the inactive orbitals. This means that there is a _redundant degree of freedom_ in the orbital optimization subproblem. Redundant degrees of freedom reliably spoil convergence. But for the same reason, the (5o,5e) active space would yield strictly exactly the same wave function (it's really just a ROHF wave function). Why not try to optimize the (5o,5e) case instead?

**Comment by MatthewRHermes** [comment]
An alternative is to _increase_ the size of the active space by adding a virtual orbital which correlates to the doubly-occupied active orbital - 5s to correlate with 4s, in this case. Doing this would remove the redundancy by permitting the occupancy of the 4s orbital to deviate from exactly 2, and would also reintroduce some risk of spin contamination (which csf_solver would obviate).

**Comment by joshz793** [comment]
Adding an extra 5s orbital solved the issue, thank you so much!
