### ISSUE TITLE
"Basis data not found" for Bromine, B3LYP/6-31G(d,p) [but is available on basissetexchange/Gaussian/GAMESS]

### ISSUE THREAD

**Issue by kshen-noble** [pyscf/pyscf#2549]
Could someone help me understand the following behavior?

I'm trying to reproduce calculations from this [paper](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0296-5) that did benchmark calculations on the QM7 molecules at the B3LYP/6-31G(d) level with GAMESS.

I'm finding that the same basis runs for some molecules, but not for others. 

In this instance I believe it's due to the Bromine atom, but it may be a broader problem. The basis set for Br is there for Gaussian and GAMESS (checked on https://www.basissetexchange.org). How would I check what is included in PySCF's basis set? How would I modify/augment the basis set that's in PySCF?

Example:
```
mol = gto.Mole()
mol.atom = """
H    -1.68580  -1.04480   5.14840
N    -1.19090  -1.15990   4.26800
C    -1.92150  -1.62270   3.33680
N    -1.45130  -1.88690   2.05250
N    -2.33640  -2.33250   1.11580
C    -3.50270  -2.49420   1.61860
S    -3.67960  -2.09570   3.32820
Br   -4.95910  -3.13270   0.59740
C    -0.09920  -1.51600   1.61700
C    -0.03240  -0.12180   1.04850
C     0.68800   0.86200   1.58430
H     0.19330  -2.26130   0.87060
H     0.54700  -1.61260   2.49120
H    -0.62010   0.05220   0.14770
H     1.26990   0.71200   2.49010
H     0.71940   1.85230   1.13930
"""
mol.basis = "6-31G(d,p)"
mol.build()
```

Troubleshooting things I tried:
- changing the basis to something like `ccpvdz` works again
- changing the `Br` to `H` also works again.

Thank you!

**Comment by xubwa** [comment]
For which basis set supports which element, you might dig into the pyscf/gto/basis directory. In the pyscf/gto/basis/__init__.py file, the relation between the basis set file and basis set name is given.
If you cannot find it in pyscf and want to use the basis set information from basis set exchange, pyscf supports the nwchem basis format, and can parse it through a basis string. Just put mol.basis='''{basis set information from bse}''' should be able to do the work for you.
The more easy to use interface to basis set exchange is also in the plan I believe.
from pyscf import gto
mol = gto.Mole()
mol.atom = """
Br    -1.68580  -1.04480   5.14840
Br   -4.95910  -3.13270   0.59740
"""
mol.basis='''
#BASIS SET: (22s,16p,5d) -> [5s,4p,3d]
Br    S
      0.1137182000E+06       0.1717696000E-02
      0.1707444000E+05       0.1316744000E-01
      0.3889576000E+04       0.6504553000E-01
      0.1097096000E+04       0.2269505000E+00
      0.3520624000E+03       0.4768357000E+00
      0.1207002000E+03       0.3583677000E+00
Br    SP
      0.2471138000E+04       0.2243687000E-02       0.3790182000E-02
      0.5893838000E+03       0.2994853000E-01       0.2995979000E-01
      0.1918738000E+03       0.1256009000E+00       0.1318228000E+00
      0.7295339000E+02      -0.9832786000E-03       0.3432708000E+00
      0.3005839000E+02      -0.6013141000E+00       0.4642345000E+00
      0.1252927000E+02      -0.4913983000E+00       0.2079387000E+00
Br    SP
      0.1096411000E+03      -0.5975683000E-02      -0.6907483000E-02
      0.3858948000E+02       0.5542122000E-01      -0.3041432000E-01
      0.1637818000E+02       0.2681200000E+00       0.4602725000E-01
      0.7221836000E+01      -0.1543606000E+00       0.3650689000E+00
      0.3263697000E+01      -0.7206306000E+00       0.4949232000E+00
      0.1465499000E+01      -0.3316437000E+00       0.2090394000E+00
Br    SP
      0.2103651000E+01       0.3029029000E+00      -0.2826714000E-01
      0.7547050000E+00      -0.2152659000E+00       0.3503065000E+00
      0.3005140000E+00      -0.9633941000E+00       0.7182446000E+00
Br    SP
      0.1090710000E+00       0.1000000000E+01       0.1000000000E+01
Br    D
      0.6225514000E+02       0.7704229000E-01
      0.1731284000E+02       0.3707384000E+00
      0.5607915000E+01       0.7097628000E+00
Br    D
      0.1746486000E+01       1.0000000
Br    D
      0.4366000000E+00       1.0000000
END'''
mol.build()

________________________________
From: kshen-noble ***@***.***>
Sent: Tuesday, December 10, 2024 12:04 PM
To: pyscf/pyscf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pyscf/pyscf] "Basis data not found" for Bromine, B3LYP/6-31G(d,p) [but is available on basissetexchange/Gaussian/GAMESS] (Issue #2549)

[External email - use caution]


Could someone help me understand the following behavior?

I'm trying to reproduce calculations from this paper<https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0296-5> that did calculations at the B3LYP/6-31G(d) level with GAMESS

I'm finding that the same basis runs for some molecules, but not for others.

In this instance I believe it's due to the Bromine atom, but it may be a broader problem. The basis set for Br is there for Gaussian and GAMESS (checked on https://www.basissetexchange.org<https://www.basissetexchange.org/>). How would I check what is included in PySCF's basis set? How would I modify/augment the basis set that's in PySCF?

Example:

mol = gto.Mole()
mol.atom = """
H    -1.68580  -1.04480   5.14840
N    -1.19090  -1.15990   4.26800
C    -1.92150  -1.62270   3.33680
N    -1.45130  -1.88690   2.05250
N    -2.33640  -2.33250   1.11580
C    -3.50270  -2.49420   1.61860
S    -3.67960  -2.09570   3.32820
Br   -4.95910  -3.13270   0.59740
C    -0.09920  -1.51600   1.61700
C    -0.03240  -0.12180   1.04850
C     0.68800   0.86200   1.58430
H     0.19330  -2.26130   0.87060
H     0.54700  -1.61260   2.49120
H    -0.62010   0.05220   0.14770
H     1.26990   0.71200   2.49010
H     0.71940   1.85230   1.13930
"""
mol.basis = "6-31G(d,p)"
mol.build()


Troubleshooting things I tried:

  *   changing the basis to something like ccpvdz works again
  *   changing the Br to H also works again.

Thank you!

**Comment by kshen-noble** [comment]
Awesome, thank you! What's the syntax for patching this Br basis set on top of the `6-31G(d,p)` basis set?

**Comment by kshen-noble** [comment]
Thanks for the note @susilehtola -- do you mean that, for example, 6-31G(d,p) might be different between one program and another? 

Or that when benchmarking to calculations from another group/program, to make sure I use the same Pople set? E.g. how 6-31G(d,p) is different from 6-31G(d)?

**Comment by kshen-noble** [comment]
Ah, thank you! I'll look into the pyscf Basis Set Exchange interface.

And will look to move beyond Pople, too -- was benchmarking against old Pople datasets to make sure I knew I was running PySCF consistently.
