### ISSUE TITLE
psi4 like standalone input/output command line run

### ISSUE THREAD

**Issue by chrinide** [pyscf/pyscf#269]
Dear Pyscf developers,

Is there any plan to implement a psi4 like standalone input/output command line run feature in pyscf?

**Comment by tberkel** [comment]
Sorry, could you be more specific about the type of functionality you have
in mind?

**Comment by sunqm** [comment]
There are two relevant projects

https://github.com/nmardirossian/PySCF_Tutorial/blob/master/user_guide.ipynb
https://github.com/PyQC/json_schema/blob/master/pyscf/from_json.py#L10

Functions like json2pyscf, run are defined in the two projects. Although they do not provide a direct cmdline parser, I believe it's straightforward to implement a python wrapper to reading stdin strings and pass the string to these functions. E.g.
```
import sys
from json_schema.pyscf.from_json import json2pyscf
json2pyscf(sys.argv[1])
```
where the stdin string is json object like
```
{
    "molecule": {"symbols": ["He", "He"], "geometry": [[0, 0, 0], [0, 0, 1]]},
    "method": "SCF",
    "options": {
        "BASIS": "STO-3G"
    },
}
```

**Comment by dgasmith** [comment]
This has evolved a bit since the PyQC days. Usually we are are starting to add JSON drivers for codes underneath our abstraction engine [here](https://github.com/molssi/qcengine). These are based off the QCSchema specs [here](https://github.com/molssi/qcschema). 

Psi4 now also has the QCSchema IO build in either from a CLI or from the API as seen in an example [here](https://github.com/psi4/psi4/blob/master/tests/json/schema-1-energy/input.py).

I am a bit busy with general [QCArchive](https://qcfractal.readthedocs.io/en/latest/qcarchive_overview.html) initiates at the moment, but I will get back to the engine and start adding more programs there in a few months. Pull requests to the engine are of course very much welcome and would mean PySCF would work automatically with the archive ecosystem.
