### ISSUE TITLE
KUHF evaluation of the number of electrons is inconsistent

### ISSUE THREAD

**Issue by iskakoff** [pyscf/pyscf#284]
in the method kuhf.nelec (https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/scf/kuhf.py#L364)
one call cell.tot_electrons(nkpts) which as we look inside the pbc.gto.cell will return the total number of electrons multiplied by nkpts which is number of k-points.

If we consider the simplest case of single hydrogen atom per unit cell, we should have spin = 1, total number of electrons per unit cell = 1, and 1 electron for spin alpha and 0 electrons for spin beta.
With this setup for even number of k-points we get an error "Electron number and spin are not consistent" and we get some results for odd number of k-points.
This behavior is obvious, because with 1 electron per unit cell and spin = 1 we have:
```
     nalpha = (nkpts + 1) // 2
```
that will be `nkpts//2` for even numbers and `nkpts//2 + 1` for odd numbers.
In this case for `nbeta = nalpha - 1` we will have for even number of k-points:
```
    nalpha + nbeta = nkpts//2 + nkpts//2 - 1 < nkpts
```
and for odd number of k-points:
```
    nalpha + nbeta = nkpts//2 + 1 + nkpts//2 + 1 - 1 = nkpts
```
But this seems wrong. Also the total number of electron per unit cell multiplied by number of k-points does not make much sense.

Is this a bug or am I missing something?

**Comment by gkc1000** [comment]
This is by design. For example, if you were to run RHF on a system with a
single hydrogen atom per unit cell, you want to consider the entire set of
points in the Brillouin zone when constructing the RHF determinant, and
within this set of occupied orbitals, the total Sz = 0. In other words,
from PySCF's perspective, the many-electron wavefunction is defined over
the full set of crystalline orbitals (at all k's), and the k points are
just symmetry labels, which is the consistent way to view things for the
many-particle state.
