### ISSUE TITLE
Question about matrix elements between periodic and non-periodic basis functions

### ISSUE THREAD

**Issue by mmorale3** [pyscf/pyscf#307]
Hi,

Is there a simple way in the pbc code to compute the overlap between the Periodic GTO basis and a single non-periodic function of the basis set (one of the gaussians)? This is surely being done right now as this is just one of the many terms needed to calculate the overlap between any 2 elements of the Periodic AO basis. The question is how to obtain this overlap without needed to implement new overlap routines? Is this easily accessible in the code?

Thank you in advance!

Miguel Morales, moralessilva2@llnl.gov

**Comment by gkc1000** [comment]
Hi Miguel, to my knowledge, there isn't an immediate solution. The
evaluation is done inside pbc.gto.intor_cross i.e. in
https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/cell.py
which takes in a molecule intor function, but the lattice summation is then
handled in the C library function in libpbc, see e.g.
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/pbc/fill_ints.c,
so things like evaluating exp(ikr) can be done quickly.

However, because the molecular GTO intor interface is exposed, it should be
reasonably straightforward to write the lattice sum yourself, i.e. you can
call gto.moleintor.getints directly for the
set of basis functions in the periodic AO basis and add them up. Examples
of how to access different components of the basis structure are in
gto.molintor. Follow up if you need more help.
Garnet

**Comment by sunqm** [comment]
My understanding is that an overlap between non-pbc and pbc AOs is equivalent to the overlap between pbc AOs. Considering the pbc-1d case, \sum_T j(r-T)  being the pbc AO, the overlap between non-pbc function i(r) and pbc AO \sum_T j(r-T) is

S1 = \sum_T \int i(r) j(r-T) dr

if both i and j are pbc AOs, the overlap is

\sum_TR \int i(r-R) j(r-T) dr = \sum_RT \int i(r) j(r-T+R) dr = \sum_R\sum_V \int i(r) j(r-V) dr = \sum_R S1 = N S1
where N is the number of cells in lattice summation

There is no difference between the two overlaps except a multiplier N. In the actual computation, we always evaluate the per cell value, i.e. scaling the integrals by 1/N, which gives S1 for the overlap of two pbc AOs. You can use cell.pbc_intor('int1e_ovlp') for AOs in the same cell or pyscf.pbc.cell.intor_cross for AOs of different cell/mol, as posted in Garnet's answer

Qiming

**Comment by mmorale3** [comment]
Thanks for the quick replies.  The periodic overlaps contain all the information I need. Thanks!
