### ISSUE TITLE
SCF vs CASCI and FCI energies for Hamiltonians with low-symmetry eri

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#350]
Greetings,

While trying to generate multi-determinant wavefunctions by means of CI calculations,
I encountered some issues (for a Hamiltonian where the electron repulsion integral has 
neither 8-fold nor 4-fold symmetry as defined in PySCF).
- in order to do a SCF calculation, one has to manually define the get_jk function
- running CASCI (with all particles and orbitals active) and FCI (with very high pspace_size)
gives different energies; moreover, depending on the studied Hamiltonian (here generated randomly), the UHF, CASCI and FCI energies can assume every possible ordering.

Can you please help me understanding why? (an example script is showed below)

thanks,
Mario

import numpy        as np
import numpy.random as rand
from   pyscf        import gto,scf,ao2mo,fci,mcscf

rand.seed(12345)
# small, random Hamiltonian
norb,nela,nelb = 7,5,3
h1 = rand.random((norb,norb))
h1 = (h1 + h1.T)
h2 = rand.random((norb,norb,norb))
h2 = np.einsum('prg,sqg->prqs',h2,h2)*0.1

mol               = gto.M()
mol.nelectron     = nela+nelb
mol.spin          = nela-nelb
mol.verbose       = 4
mol.incore_anyway = True

mf            = scf.UHF(mol)
mf.energy_nuc = lambda *args: 0.0
mf.get_hcore  = lambda *args: h1
mf.get_ovlp   = lambda *args: np.eye(norb)
mf._eri       = h2
# in presence of 1-fold symmetry, one needs to manually define the jk functions
def get_jk_loc(mol=None,dm=None,hermi=None):
 vj = np.zeros((2,dm[0].shape[0],dm[0].shape[1]))
 vk = np.zeros((2,dm[0].shape[0],dm[0].shape[1]))
 for js in range(2):
  vj[js,:,:] = np.tensordot(h2,dm[js],axes=((0,1),(1,0)))
  vk[js,:,:] = np.tensordot(h2,dm[js],axes=((1,2),(0,1)))
 return vj,vk
mf.get_jk = get_jk_loc
E = mf.kernel(initial_guess='1e')
if(not mf.converged):
 mf  = mf.newton()
 E   = mf.kernel(mf.make_rdm1())
print "SCF energy    ",E
print "SCF stability "
mf.stability()

mycas = mcscf.UCASCI(mf,norb,(nela,nelb))
mycas.kernel()
#mycas.analyze() # uncommenting this line, the program crashes

cisolver           = fci.direct_nosym.FCI()
cisolver.verbose   = 5
cisolver.max_cycle = 100
cisolver.conv_tol  = 1e-8
e,fcivec = cisolver.kernel(h1,h2,norb,(nela,nelb),ecore=0.0,pspace_size=10000)
print "FCI energy ",e

**Comment by sunqm** [comment]
1-fold symmetry ERI tensor was supported in both master and dev branch. It's not required to define J/K builder in SCF methods.

It should be noted that the building J, K matrices this may break the hermitian symmetry. The so-obtained Fock matrix may also not have hermitian symmetry. The diagonalization function in SCF only supports hermitian matrix unless you redefine the SCF.eig methods. Without hermitian symmetry in Fock, the second order SCF code (.newton) does not make too much sense since the optimization is carried out based on the assumption of hermitian symmetry in Fock.

FCI module does not support non-hermitian hamiltonian. The direct_nosym module is not able to give reasonable FCI solution for non-hermitian Hamitonian, alghouth it allows to contract the non-hermtian Hamiltonian to a FCI vector. The reason is similar to the issue in SCF, symmetric diagonalization is hard coded in the FCI class unless you redefine the FCI.eig method.

UCASCI also does not support non-hermitian Hamitionian because its default FCI solver only supports the hermtian case. Moreover, the integral evaluation code in UCASCI also assumes hermtian integrals only. Here to support non-hermitian requires to modify the UCASCI.get_h2eff and UCASCI.get_h1eff methods.
