### ISSUE TITLE
Full set of Natural Orbitals from CASSCF

### ISSUE THREAD

**Issue by CDilek** [pyscf/pyscf#352]
Hi,

How can I obtain the full set of natural orbitals (i.e. as opposed to just those in the active space) from a CASSCF calculation?  I'd like to examine the orbital coefficients, and visualize them.  The script I'm using is below - while the natural orbitals in the active space are printed after the CASSCF calculation, I don't think that the other orbitals that are written to the molden file, and then printed, are...

mc = mcscf.CASSCF(m,ncas=nactorbs,nelecas=nactelec)
mc.natorb = True   
mc.kernel()

with open('CAS_orbs.molden', 'w') as f1:
    molden.header(mol, f1)
    molden.orbital_coeff(mol, f1, mc.mo_coeff, ene=m.mo_energy, occ=m.mo_occ)  # prints CAS orbitals, but HF energies/occupancies

aos=mol.ao_labels()
nbasis = mol.nao_nr()

for MO in range(0, nbasis):
    print( "CASSCF orbital # %d; MF occupancy: %d"  % (MO, m.mo_occ[MO]) )
    for AO in range(0, nbasis):
        print aos[AO][:], mc.mo_coeff[1, AO]   # print spin-down orbital coefficients

**Comment by gkc1000** [comment]
Hi CDilek. Strictly speaking, the natural orbitals in CASSCF outside the
active space are not uniquely defined. This
is because they are eigenvectors of the DM, and the DM is strictly zero
outside of the active space, so all such eigenvectors have
zero eigenvalue and may be freely rotated.

If you nonetheless want *some* kind of natural orbitals in the virtual
space i.e. some choice of those eigenvectors with zero eigenvalue, you can
simply diagonalize the DM produced by CASSCF, this is accessed by
make_rdm1() [https://sunqm.github.io/pyscf/mcscf.html]. Alternatively you
may not really want the natural orbitals at all, but rather the casscf fock
matrix eigenvectors, this can be accessed by canonicalize().

**Comment by gkc1000** [comment]
I'm checking in on this, if there are no further problems, I will close the issue.

**Comment by CDilek** [comment]
Thank you so much. Yes, you can close this issue.
