### ISSUE TITLE
FCIDUMP for UHF

### ISSUE THREAD

**Issue by ramadugu** [pyscf/pyscf#358]
I am trying to run a UHF calculation of H2 and then generate a FCI Dump file but it gives the following error (whether I use chkfile or the SCF object:

Overwritten attributes  get_occ  of <class 'pyscf.scf.uhf.UHF'>
Traceback (most recent call last):
  File "h2.py", line 19, in <module>
    tools.fcidump.from_chkfile('h2.fcidump', 'h2.chk',tol=1e-15,float_format=' %.16g')
  File "/Users/sramadug/pyscf-1.6.1/pyscf/tools/fcidump.py", line 102, in from_chkfile
    write_hcore(fout, h, nmo, tol, float_format)
  File "/Users/sramadug/pyscf-1.6.1/pyscf/tools/fcidump.py", line 72, in write_hcore
    h = h.reshape(nmo,nmo)
ValueError: cannot reshape array of size 16 into shape (2,2)

The python script I used:

from pyscf import gto, scf, mp, lib, tools

h2 = gto.Mole(symmetry=False)
h2.verbose = 7
h2.output = 'h2.log'
lib.num_threads(4)
h2.atom ="""
H  0.00000000  0.00000000  0.86834470;
H  0.00000000  0.00000000  1.26834470
"""
h2.basis = 'sto3g'
#h2.spin = 1
h2.build()
mf = scf.UHF(h2)
mf.chkfile = 'h2.chk'
mf = scf.addons.dynamic_sz_(mf)
#mf.init_guess = 'minao'
mf.kernel()
tools.fcidump.from_chkfile('h2chk.fcidump', 'h2.chk',tol=1e-15,float_format=' %.16g')
tools.fcidump.from_scf(mf,'h2scf.fcidump',tol=1e-15,float_format=' %.16g')

**Comment by jamesETsmith** [comment]
@ramadugu currently PySCF doesn't support generating FCIDUMP files from UHF (or GHF) methods

**Comment by ramadugu** [comment]
Thank you, James.

**Comment by YingzhouLi** [comment]
> @ramadugu currently PySCF doesn't support generating FCIDUMP files from molecules using UHF (or GHF) methods

Is it support now? I found that in the most recent version, the function `pyscf.tools.fcidump.from_scf` still does not support UHF-SCF calculation output.

**Comment by ndattani** [comment]
@sunqm I think this was "closed as completed" in error. It was closed as "completed" when @jamesETsmith said that writing an FCIDUMP file for a UHF calculation, is not yet supported; but as @YingzhouLi pointed out, it is still not supported, so the "issue" was not solved or "completed".

I don't have the privileges to re-open this though.

**Comment by ndattani** [comment]
@fishjojo, @jamesETsmith, @YingzhouLi, @ramadugu there is someone making an attempt at this [here](https://mattermodeling.stackexchange.com/q/13172/5) but they may need some guidance to help them get into PySCF.

**Comment by bogdanoff** [comment]
There is also an implementation in https://github.com/pyscf/fciqmc :
https://github.com/pyscf/fciqmc/blob/ee98fb44a4ed3010d2f8d0d1ef447692b8dadf9d/pyscf/fciqmcscf/fciqmc.py#L308

**Comment by ndattani** [comment]
@bogdanoff thanks! Based on the commit history and "Git blame", it looks like this was written by @sunqm. Why would the functionality for writing the FCIDUMP be written in a file specific to FCIQMC, rather than in a more general place like pyscf.tools.fcidump, or pyscf.ao2mo? I have written some comments about that here: https://mattermodeling.stackexchange.com/a/13262/5.

**Comment by sunqm** [comment]
FCIDUMP for UHF was initially used by fciqmc module only. This module was later removed from the core branch.

Since the UHF FCIDUMP is available in fciqmc repo, I'll close this issue. If you wish to have this feature in pyscf core branch, please feel free to reopen the issue and add a 'request feature' label.
