### ISSUE TITLE
IP(EA)-EOM-CCSD with the koopmans=True guess

### ISSUE THREAD

**Issue by hungpham2017** [pyscf/pyscf#377]
Greetings,

I have a question over the use of the attribute **koopmans = True** in an IP(EA)-EOM-CCSD calculation. Does that mean one specifically target the first excitation? and that the higher roots if requested using this guess maybe not accurate? I realize that in some of my calculations this option makes higher roots strange, i.e., some are no longer degenerate or breaking k-point symmetry.
Thank you. I greatly appreciate any help.

HP

**Comment by tberkel** [comment]
Hi Hung,

Typically, iterative eigensolvers will find eigenvalues in order of increasing energy.  The goal of `koopmans=True` is to target excited states based on the eigenvector character in addition to the energy.  In particular, it tries to find eigenvalues whose eigenvectors have large R1 amplitudes (as opposed to large R2 amplitudes).  A large R1 amplitude means that the excited state is primarily characterized by single electron addition or removal (for EA/IP), i.e. it is a Koopmans-like excitation, rather than an excited state that is primarily characterized as a 2p1h (double electron addition + single removal) or 2h1p.  For each EOM eigenvalue that is returned, a quantity called `qpwt` (quasiparticle weight) is also printed, which is the magnitude of the R1 part of the EOM (R1,R2) vector.  Excitations with a large `qpwt` (close to 1) are Koopmans-like excitations.  These are also the states that will have the largest intensity in the one-particle spectral function or the photoemission spectrum.

The same discussion also applies to EE-EOM, where `koopmans=True` finds states that are dominated by neutral single-excitation character (rather than double excitations).

**Comment by hungpham2017** [comment]
Thank you very much for your explanation. So one uses `koopmans=True`  when constructing the quasi-particle bands around the fermi level as discussed in page 1212 of the [CCSD](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b00049) paper?

**Comment by tberkel** [comment]
Yes, in the periodic setting, the band structure should be plotted using
the Koopmans excitation energies; other eigenvalues correspond to so-called
satellite peaks.  Convergence with Davidson can be finicky, so the Koopmans
energies could be equivalently obtained by using `koopmans=False` and
ignoring any roots with a small `qpwt`, or using `koopmans=True` (and
confirming that all found roots have a large `qpwt`!).

**Comment by hungpham2017** [comment]
It is very clear now. Thank you so much for your prompt response.
