### ISSUE TITLE
k-CCSD vs supercell-CCSD

### ISSUE THREAD

**Issue by arshamsam** [pyscf/pyscf#413]
Dear developers, 

I checked the example 24-k_points_vs_gamma.py in pyscf/examples/pbc/. 
It gives the following results:

Difference between gamma/k-point mean-field calculation = 6.19770901266747e-11
Difference between gamma/k-point ccsd calculation = 0.061680422318234
Difference between gamma/k-point ip-eomccsd calculation = 0.644030612851176
Difference between gamma/k-point ea-eomccsd calculation = 0.0173786446853493

I checked the difference between the correlation energies: 

RCCSD converged (Supercell), two atoms in Sim. cell
E(RCCSD) = -21.24904589564981  E_corr = -0.1872357226992221   
E(RCCSD)/atom = −10.62452295    ;  E_corr/atom = -0.0936

RCCSD converged (k-mesh) , one atom 2 k-points 
E(RCCSD)/atom = -10.68620337008116  E_corr/atom = -0.15529

the difference between gamma/k-point mean-field calculations is what we expect, but it's not the case for CCSD and the E_corr. What's the source of discrepancy and which one is more accurate?  I compared the CCSD-E_corr with FCIQMC and DMC correlation energies and I found that  k-CCSD agrees  with FCIQMC and DMC better than supercell-CCSD. 

Best, 
Sam

**Comment by gkc1000** [comment]
Hi - HF can be run with exxdiv=None or ewald, but will probably always converge better with exxdiv=ewald in the SCF (aside from other things) because the occupied orbitals are shifted downwards.

CC (and many-body calculations in general) implicitly use exxdiv=None, otherwise the Hamiltonian is not correct. 

CCSD and FCIQMC will not agree exactly for 16 electrons, although this difference seems quite large, maybe because the hydrogens are all a bit dissociated from each other.

**Comment by verena-neufeld** [comment]
Hi @arshamsam , has this been resolved?

**Comment by verena-neufeld** [comment]
@arshamsam , thanks for having opened this issue. 
@arshamsam , @fishjojo , @sunqm , it seems that this has been resolved?
