### ISSUE TITLE
How to access the z-vector relaxed density for TDDFT calculated states?

### ISSUE THREAD

**Issue by tzyii** [pyscf/pyscf#454]
It seems that z-vector method were implemented.

**Comment by sunqm** [comment]
Is the z-vector density referred to the density matrix for analytical gradients of excited state?

**Comment by tzyii** [comment]
Yes. This density is used for population analysis of excited states in gaussian.

**Comment by sunqm** [comment]
I don't know what is the proper definition of density matrix for TDDFT excited states. The z-vector relaxed density the gradients code computed, IMO, cannot be used as the electron density because it includes the contribution of orbital response. I guess the population analysis is likely based on the TDA (CIS) density. Here is the example for CIS density
https://github.com/pyscf/pyscf/blob/master/examples/tddft/22-density.py

**Comment by tzyii** [comment]
I know little about the corresponding theory. In the document of G16 (http://gaussian.com/density/), IMO, density=ci (default for TDDFT) and density=rhoci refer to the relaxed and unrelaxed density. And the the doucument say the use of density=rhoci is discouraged (the 'option' page), and density=ci is the default for density=current for TDDFT calculation. I don't konwn which is perfered, I just konwn the behavior in G16. 😅😅😅
