### ISSUE TITLE
Scaling of CASSCF in PySCF

### ISSUE THREAD

**Issue by br2575** [pyscf/pyscf#486]
What is the scaling of the CASSCF implementation in PySCF with system size N?
If Hartree-Fock's is N^4, then is CASSCF's N^4 with an exponential dependence on the number of active orbitals selected?

**Comment by gkc1000** [comment]
It's best to separate out the act orbitals in the scaling since (usually)
they don't scale with N.
Then, the CASSCF "FCI" part will scale like Nact4 * exp(Nact), but the full
N dependence comes
from the integral transformation step, which is sth like Nact * N^4
(without exponential dependence on Nact).
In addition there can be many smaller integral transformations during the
microiterations as explained in https://arxiv.org/pdf/1610.08394.pdf

**Comment by br2575** [comment]
Thanks, Garnet. Is the CASSCF "FCI" part completely independent of the size of the system N then?
For estimating the amount of a time a big system calculation would take from a small systems calculation, should we just use the integral transformation step since that includes the full N dependence?

**Comment by gkc1000** [comment]
If Nact is fixed, then yes

**Comment by gkc1000** [comment]
Closing this issue, reopen if further questions
