### ISSUE TITLE
problem of pyscf interfacing block

### ISSUE THREAD

**Issue by lqhenwunai** [pyscf/pyscf#489]
Dear all,

I have a problem of importing the dmrgscf in pyscf. I downloaded the precompiled binary files through here for Block-1.5 (stackblock):
https://sanshar.github.io/Block/overview.html#use-block-with-pyscf-package

and modify the settings.py in the dmrgscf folder as following:

\# To install Block as the FCI solver for CASSCF, see
\#       http://sunqm.github.io/Block/build.html
\#       https://github.com/sanshar/Block
BLOCKEXE = '/home/pyscf/pyscf/dmrgscf/Block/block.spin_adapted-1.5.3'
BLOCKEXE_COMPRESS_NEVPT = '/home/pyscf/pyscf/dmrgscf/block.spin_adapted-1.5.3-serial'
\#BLOCKSCRATCHDIR = os.path.join('./scratch', str(os.getpid()))
BLOCKSCRATCHDIR = os.path.join(lib.param.TMPDIR, str(os.getpid()))
\#BLOCKRUNTIMEDIR = '.'
BLOCKRUNTIMEDIR = str(os.getpid())
MPIPREFIX = 'mpirun'  # change to srun for SLURM job system
BLOCKVERSION = None

However, I still get the error message of importing dmrgscf module. 

Any suggestions?

Many thanks,

**Comment by jamesETsmith** [comment]
@lqhenwunai, can you post the error?

**Comment by lqhenwunai** [comment]
@jamesETsmith 

Hi James, Thanks for your reply. The error message is like:

Traceback (most recent call last):
  File "nevpt2.py", line 24, in <module>
    from pyscf import dmrgscf
ImportError: cannot import name dmrgscf

For another questions,  I install the pyscf on another machine with yum install pyscf (something like that). But in my /python3.6/site-packages/pyscf folder, the dmrgscf folder is not present. How do I fix it?

Many thanks.

**Comment by jamesETsmith** [comment]
@lqhenwunai, if that is the `nevpt2.py` from the `mrpt` module then I think you may be working from an older version of PySCF, try pulling the latest version (which doesn't have that import statement) and hopefully things will work. 

As for the pip install, I believe that dmrg isn't included in the Python wheel because it requires outside software (Block) to run. When using modules like `dmrgscf`, you will probably have to build PySCF yourself.

**Comment by lqhenwunai** [comment]
many thanks
