### ISSUE TITLE
31-cr2_scan example does not use solution from smaller CAS

### ISSUE THREAD

**Issue by h-larsson** [pyscf/pyscf#510]
Hi,

in ```examples/dmrg/31-cr2_scan/cr2-scan.py```, first a CAS(12,12) calculation is performed and afterwards a CAS(12,42). In the comments, it is written that the CAS(12,42) calculation reuses the CAS(12,12) orbitals. However, it does not look like this is the case. 
Probably, 
```    mc1.kernel()```
in https://github.com/pyscf/pyscf/blob/master/examples/dmrg/31-cr2_scan/cr2-scan.py#L104
should be replaced by
```    mc1.kernel(mc.mo_coeff)```,
or is there also a way to reuse the smaller CI vector?

**Comment by sunqm** [comment]
Thanks for catching this problem in the example. It's fixed in recent updates.

For transferring small CI vector to CI vector in large active space, the new example `https://github.com/pyscf/pyscf/blob/master/examples/fci/33-rotate_wfn.py` is relevant. The transformation in the dmrg example involves the data structure convention between the pyscf FCI wfn vector and the wavefunction of the external library, like the seleted CI program or DMRG program. That was not supported.
