### ISSUE TITLE
UKS object cannot be initialized

### ISSUE THREAD

**Issue by alexmir18** [pyscf/pyscf#513]
Hi,
The program cannot do "mf = dft.UKS(mol)" - it complains that 3 arguments are given instead of 2 to uks.UKS. I noticed that uks.UKS(mol, *args) was replaced by uks.UKS(mol, xc) in dft/__init__.py in the newer pyscf version. Changing it back fixes the issue.

Alex

**Comment by tberkel** [comment]
I can't reproduce this in v1.7.0.  Can you provide a minimal script that
fails?  `UKS` in `__init__.py` automatically sets the `xc` kwarg if it is
not specified, which is then passed to `uks.UKS(mol, xc)`

**Comment by alexmir18** [comment]
mol = gto.M(atom='H 0 0 0', spin=1)
mf = dft.UKS(mol)
It turns out the issue is due to two versions of pyscf installed on the machine, so that the newer pyscf module(module "pyscf_17") keeps using older pyscf files (module "pyscf"), since "import pyscf" is hard-coded in .py files. Could you suggest the best way to keep two pyscf versions? I added some routines to the previous version, so I would like to keep it for back-compatibility.

**Comment by fishjojo** [comment]
You can set PYTHON_PATH to the top directory of the pyscf you need.

**Comment by jamesETsmith** [comment]
If you're going to be working with multiple versions of any Python package, PySCF included, I would strongly recommend using virtual environments to keep your package separate and safe. 

I would suggest using [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html#installation) or [virtualenv](https://virtualenv.pypa.io/en/latest/). From a virtual environment you can pip/conda install a stable version of PySCF and they will be isolated within this environment, i.e. won't get mixed up between different versions. You can even build PySCF from source and then use `python -m pip install -e .`  inside the main PySCF directory to install that version to your currently activated environment.

In general, editing the `$PYTHONPATH` env variable is a viable option, but as you've seen it requires some care, whereas virtual environments are safeguarded against these kinds of problems by design.

**Comment by alexmir18** [comment]
Thank you for the detailed response!
