### ISSUE TITLE
Is it possible to obtain V_ext(r)?

### ISSUE THREAD

**Issue by sakuraiiiii** [pyscf/pyscf#605]
Hi,I want to obtain the external potential,i.e. the field formed by the arrangement of ions,in real space.Is there a way to obtain the external potential of a specific material system with ```pyscf```?Thank you.

**Comment by tberkel** [comment]
Not sure if you're asking about a molecule or a periodic solid ...

One doesn't really need pyscf to obtain this potential for molecules.  It's
defined by only the locations and charges of the ions,
v_{ext}(r) = \sum_{A} Z_A / |r-R_A|

For a periodic system, the potential would be
v_{ext}(r) = \sum_{A} Z_A \psi(r-R_A) + (arbitrary constant)
where \psi(r) is the potential at r due to a point charge at the origin,
including its periodic images and a neutralizing uniform background.  This
is most efficiently calculated by Ewald summation, and the expression can
be found in many papers and books.  I don't think pyscf has any black-box
functions to compute this potential, but it uses Ewald summation and the
potential \psi(r) to calculate the nuclear-nuclear interaction energy,
E_{NN} = \sum_{A<B} Z_A Z_B \psi(R_A-R_B) + (another constant)
This is done in the `ewald()` function
https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/cell.py#L715
which may guide you in writing your own function to evaluate the external
potential for a given `Cell` object.

**Comment by sakuraiiiii** [comment]
Yep,what I want to implement is the potential for a periodic system.Thak you very much!

**Comment by sakuraiiiii** [comment]
Hi,I have a similar question.In DFT framework of ```pyscf```,could we get the $V_{ext}(r)$ with pseudo potential?

**Comment by gkc1000** [comment]
The pseudopotential is not a local operator, i.e. it is V(r,r').

**Comment by sakuraiiiii** [comment]
Ok,thank you.
