### ISSUE TITLE
orbital optimized mp2 for unrestricted scheme and OO-RI-MP2

### ISSUE THREAD

**Issue by nesquik91** [pyscf/pyscf#679]
Dear all,

Hi, I found a nice OO-MP2 example in the 42-omp2.py file but having trouble doing an unrestricted open-shell scheme.
Is it possible to make an unrestricted scheme example file? 
One more thing is, if I do the calculation like below, is that a proper option for OO-RI-MP2?
Thank you very much!

class MP2AsFCISolver( object ):
  def kernel (self , h1 , h2 , norb , nelec , ci0=None , ecore =0, ** kwargs ):
    # Kernel takes the set of integrals from the current set of orbitals
    fakemol = pyscf.M( verbose =8)
    fakemol.nelectron = sum( nelec )
    fake_hf = fakemol.RHF()
    fake_hf._eri = h2
    fake_hf.get_hcore = lambda * args: h1
    fake_hf.get_ovlp = lambda * args: np.eye(norb)
    # Build an SCF object fake_hf without SCF iterations to perform MP2
    fake_hf.mo_coeff = np.eye(norb)
    fake_hf.mo_occ = np.zeros(norb)
    fake_hf.mo_occ[:fakemol.nelectron//2] = 2
    self.mp2 = fake_hf.MP2().run()
    return self.mp2.e_tot + ecore , self.mp2.t2

mf = mol.RHF().density_fit().run()
mc = pyscf.mcscf.CASSCF(mf , mol.nao , mol.nelectron )
mc.fcisolver = MP2AsFCISolver()

**Comment by sunqm** [comment]
Question 1.
If unresctricted scheme refers to a combination of UMP2 with CASSCF solver, the answer is no. CASSCF has to be called with spin-adapted solver. UMP2 solver in principle can be combined with the mcscf.UCASSCF module using a similar adapter code. Please note that UCASSCF solver may not work well with low-spin systems. It may end up with a totally wrong spin state.

Question 2.
`mc.internal_rotation = True` has to be set. `mc.conv_tol` should be loosen a little bit otherwise it may not converge.

**Comment by verena-neufeld** [comment]
Hi @nesquik91 , has this been resolved?

**Comment by verena-neufeld** [comment]
@nesquik91 , thanks for posting this issue.
@nesquik91 , @fishjojo , @sunqm , it seems that this issue can be closed?

**Comment by sunqm** [comment]
Please feel free to reopen the issue
