### ISSUE TITLE
Total energy differences among pyscf and other codes

### ISSUE THREAD

**Issue by yaoyi92** [pyscf/pyscf#688]
I try to use pyscf to calculate a small molecule and compare the total energy with some other QM codes. pyscf result seems to be a little bit inconsistent with the other codes. I have checked the integration grid and it seems already converged. This behavior happens for other functionals and even HF calculation. Can someone point me to the origin of this difference.
 
| code   |      total energy (a.u.)      |
|----------|:-------------:|
| pyscf | -114.364992564   |
| gaussian |    -114.367370061   |
| gamess | -114.367396666 |
| nwchem |  -114.3673996141 |

input for pyscf
------------------
from pyscf import gto, scf, dft
mol = gto.M(atom='''
C        0.000000    0.000000             -0.542500
O        0.000000    0.000000              0.677500
H        0.000000    0.9353074360871938   -1.082500
H        0.000000   -0.9353074360871938   -1.082500
            ''',
            verbose = 6,
            basis='6-31g**')
mf = scf.RKS(mol)
mf.xc = 'pbe'

mf.kernel()

input for gaussian
--------------
#p PBEPBE/6-31G** sp NoSymmetry

Title

0 1
C        0.000000    0.000000             -0.542500
O        0.000000    0.000000              0.677500
H        0.000000    0.9353074360871938   -1.082500
H        0.000000   -0.9353074360871938   -1.082500

input for gamess
---------------
 $CONTRL SCFTYP=RHF DFTTYP=USELIBXC RUNTYP=GRADIENT $END
 $BASIS  GBASIS=N31 NGAUSS=6 NDFUNC=1 NPFUNC=1 $END
 $LIBXC FUNCTIONAL=PBE $END

 $DATA
Title
C1
C    6.0    0.000000    0.000000             -0.542500
O    8.0    0.000000    0.000000              0.677500
H    1.0    0.000000    0.9353074360871938   -1.082500
H    1.0    0.000000   -0.9353074360871938   -1.082500
 $END

input for nwchem
------------------
echo
start test
geometry
C        0.000000    0.000000             -0.542500
O        0.000000    0.000000              0.677500
H        0.000000    0.9353074360871938   -1.082500
H        0.000000   -0.9353074360871938   -1.082500
end

basis
 C library 6-31g**
 O library 6-31g**
 H library 6-31g**
end

dft
  xc xpbe96 cpbe96
end

task dft energy

**Comment by 1234zou** [comment]
This is mainly due to the inconsistency of spherical harmonic/Cartesian gaussian functions used in various quantum chemistry software packages. For example, the default settings are shown as follows:
In Gaussian, 6-31G(d,p) uses (6D,7F);
In GAMESS, all Cartesian functions, i.e. (6D, 10F, 15G, 21H);
In PySCF, all spherical harmonic functions, i.e. (5D, 7F, 9G, 11H);
In ORCA, all spherical harmonic functions (and only spherical functions are supported).
I'm not familiar with NWChem.

6D has 1 more basis function than that of 5D, and 10F has 3 ones more than 7F. Thus by using Cartesian functions, the number of basis functions (Contracted GTOs) is slightly larger than the number of basis functions using spherical harmonic functions. And of course, the former RHF energy will be slightly lower.

In order to strictly compare RHF energies in different software, you should explicitly set the type spherical/Cartesian. E.g.
In Gaussian, specify keywords '5D 7F' means using all spherical harmonic functions; while '6D 10F' means using all Cartesian functions;
In PySCF, it is 'mol.cart=True' or 'mol.cart=False';
In GAMESS, maybe specify ispher=+1 in $CONTRL section will do some help, but not commonly used.
In ORCA, you have no choice but all spherical, etc.

By the way, I suggest you test the RHF/ROHF/UHF energies among different packages, not DFT. Because the quality of integral grid in DFT will affect its final electronic energy, and more other factors.

**Comment by yaoyi92** [comment]
Thank you so much. This explains it.
