### ISSUE TITLE
DHF integrals being real for atoms and two-atom molecules

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#732]
Hi there,
I have been doing relativistic ci calculations using the FCIDUMP files generated by pyscf. I recently noticed something strange. If the molecule has less than three atoms, then all the integrals are real valued, which is not what I would expect, but it still gives the correct ZFS splitting compared with results from BAGEL's integrals and also DIRAC's results.
You can find a script that reproduces this problem below. It writes FCIDUMP for C atom, NH molecule and H2O molecule. Only integrals for H2O molecule has complex valued integrals. I'm not sure the recently supported kramer-restricted solver is able to resolve this problem since I have no idea get zquatev to work.
[https://gist.github.com/xubwa/9e4c997bf4426d54693c3225881cd4d0](url)
Xubo

**Comment by zhendongli2008** [comment]
I'm not sure whether this is an issue of the program. But for atom, the MO
integrals should be real due to symmetry reasons. For polyatomic molecules,
if the symmetry of the molecule is high, then it is also possible that the
MO integrals are real.

Best,
Zhendong

Xubo Wang <notifications@github.com> 于2020年10月10日周六 下午4:29写道：

**Comment by xubwa** [comment]
Thank you Zhendong, I recently read more on the symmetry direction. So I believe it is due to the fact that although these symmetries are not explicitly exploited, but they still managed to take over the results at some really high symmetry cases such as linear molecules.
