### ISSUE TITLE
Unfavorable dmrg schedule?

### ISSUE THREAD

**Issue by h-larsson** [pyscf/pyscf#740]
In the standard DMRG schedule ( https://github.com/pyscf/pyscf/blob/master/pyscf/dmrgscf/dmrgci.py#L228 ), the Davidson convergence is sequentially decreased while the noise is held constant at 5e-5. I don't see how it makes sense to have, e.g., a Tol of 1e-10 while the noise is still 5e-5. In block's default schedule, Tol is set to 5e-6 ( https://github.com/sanshar/StackBlock/blob/master/Schedule.C#L40 ).

**Comment by sanshar** [comment]
The schedule is set such that while the two site algorithm is being
executed the noise is always non-zero which helps DMRG from getting stuck
in a local minimum. But after a sufficient number of two-site sweeps the
algorithm switches to one-site sweep and the noise is made zero. This makes
the energy monotonically converge to a minimum for the given M.
   The default settings in pyscf are often chosen conservatively so that
robustness is favored over small CPU time. However, for a given application
it is quite likely that the schedule can be modified to reduce the CPU
time. A user should certainly use this freedom when they have enough
background knowledge to do so.

Sandeep.

**Comment by verena-neufeld** [comment]
Hi @h-larsson , has this been resolved?

**Comment by h-larsson** [comment]
Looks like 08b8a22 took care of this.
