### ISSUE TITLE
Molden file to Mole

### ISSUE THREAD

**Issue by ssnam92** [pyscf/pyscf#758]
Dear PySCF developers

It seems that `tools.molden.load` loads Mole object incorrectly
For example, 1st cc-pVTZ basis set of oxygen 
```
O    S
  15330.0000000              0.0005080             -0.0001150
   2299.0000000              0.0039290             -0.0008950
    522.4000000              0.0202430             -0.0046360
    147.3000000              0.0791810             -0.0187240
     47.5500000              0.2306870             -0.0584630
     16.7600000              0.4331180             -0.1364630
      6.2070000              0.3502600             -0.1757400
      0.6882000             -0.0081540              0.6034180
```
and in Molden file (generated by ORCA), basis info
```
    15330.0000000000         0.5107820689
     2299.0000000000         0.9520320559
      522.4000000000         1.6143309227
      147.3000000000         2.4433650471
       47.5500000000         3.0486061870
       16.7600000000         2.6183461361
        6.2070000000         1.0052339944
        0.6882000000        -0.0044964733
```
Exponents and their orders are the same.

If I try
```
import numpy as np
from pyscf import gto,tools

mol1=gto.M(atom='''
O  0.0 0.0 0.0
H  1.0 0.0 0.0
H  0.0 0.9 0.3
''',basis='cc-pVTZ',verbose=0)

mol2, mo_eng, mo_cof, mo_occ,_,_=tools.molden.load('orca.molden')

a=mol1.bas_ctr_coeff(0)[:,0]
b=mol2.bas_ctr_coeff(0)[:,0]
expos=mol1.bas_exp(0)
for i in range(8):
  N=(expos[i]*2/np.pi)**(3/4) #Normalization constant for S function
  print('{:12.8f} {:12.8f} {:12.8f}'.format(a[i],b[i],a[i]*N/b[i]))

```
gives
```
Unknown section TITLE
  0.00052020   0.05543436   9.21417896
  0.00402334   0.10332251   9.21417896
  0.02072908   0.17520073   9.21417896
  0.08108233   0.26517447   9.21417896
  0.23622635   0.33086032   9.21417896
  0.44351821   0.28416489   9.21417896
  0.35867059   0.10909643   9.21417896
 -0.00834980  -0.00048800   9.21417904
```
A consistent third column indicates that there may be some sort of redundant treatment for the contraction coefficient.

`mol1` and `mol2` gives different HF energies, too:
```
from pyscf import scf
mf1=scf.RHF(mol1)
mf2=scf.RHF(mol2)
print(mf1.kernel())
print(mf2.kernel())
```
```
-76.04812933862787
-73.13816712448269
```
`mol2` gives too high HF energy.

**Comment by fockeke** [comment]
I'm not a PySCF developer, but the issue is very interesting to me and my project. Could you add the orca.molden file to the issue?

**Comment by ssnam92** [comment]
@fockeke 
[orca.molden.txt](https://github.com/pyscf/pyscf/files/5517024/orca.molden.txt)

**Comment by 1234zou** [comment]
This is not necessarily the problem of PySCF. Or maybe neither your .molden file or PySCF's reading is correct.

It is not recommended to read .molden file as initial guess of orbitals, since the molden format is not strictly/rigorously followed by developers of various quantum chemistry packages. Many software packages generate non-standard molden files (e.g. some MO coefficients are multiplied by -1 in ORCA .molden). Some alternative approaches are listed below

(1) use Molden2AIM (https://github.com/zorkzou/Molden2AIM) to generate a standard molden file;
(2) use Multiwfn (http://sobereva.com/multiwfn/) to read in your ORCA .mkl/.molden file and export a new .molden file;
(3) I've also written some utilities (https://gitlab.com/jxzou/mokit) which can solve this problem, e.g.
fch2mkl: generate ORCA .mkl and .inp files from a Gaussian .fch file.
mkl2fch: transfer MOs from .mkl file back to .fch file
fch2py: read MOs from a Gaussian .fch file in a PySCF job.
Use the above 3 utilities you can read MOs in PySCF.

Good luck!

Added by myself at 2026-Jun-18:
Nowadays we can simply use the function `load_mol_from_molden`. For example,
```python
from mokit.lib.gaussian import load_mol_from_molden
mol = load_mol_from_molden(molden='h2o.molden', program='orca')
```
This function supports not only the ORCA molden file, but also many other molden files generated by >10 quantum chemistry software packages. One can simply specify `program='pyscf'`, `program='molpro'`, etc.

**Comment by John-zzh** [comment]
I'm not a developer either, but I ran into the same problem as yours. My solution is:
in the pyscf/tools/molden.py file, function
`def load(moldenfile, verbose=0):`
comment out `sys.stderr.write('Unknown section %s\n' % sec_title)`
and add `pass`.

Thats works well for me :-)
