### ISSUE TITLE
Why are mo_ints 2d matrices instead of 4d?

### ISSUE THREAD

**Issue by PabloAMC** [pyscf/pyscf#867]
This will probably be a quite basic question, but confuses me 
I am doing something like
```
mol = gto.M(atom='H 0 0 0; H 0 0 1')
mf = scf.RHF(mol).run()
mo_ints = ao2mo.kernel(mol, mf.mo_coeff)
```
But instead of a 4d matrix, `mo_ints` is a 2d matrix. I thought that `mo_ints` would represent something like `h_{ijkl}` from the Hamiltonian $$H= \sum_{ij} h_{ij} a_i a_j^\dagger +  \sum_{ijkl} h_{ijkl} a_i a_j^\dagger a_k a_l^\dagger $$ in the Molecular Orbital basis.

And I also thought that `mf.mo_coeff` was the basis change matrix from Atomic Orbitals to Molecular Orbitals, but it confuses me because it is not orthonormal, as a rotation should be. What is it then?
Sorry for this simple question 😅

**Comment by Majokux** [comment]
You are right that those `mo_ints` represent the two-electron integrals of the Hamiltonian (in chemical ordering "(11|22)") -
but you can save these integrals more compact by making use of the symmetry (ab|cd) = (ba|dc) for real orbitals - that is, you only store those combinations in which b<= a and d<= c. This reduces the size from N^4 to (N*(N+1)/2)^2, however each index in the matrix you obtain represents a _pair_ of MOs. You can get the entire N^4 object by adding `compact=False` to the `ao2mo` call (it might still be a 2D matrix; you just need to reshape it)


>And I also thought that mf.mo_coeff was the basis change matrix from Atomic Orbitals to Molecular Orbitals

That's correct. The MOs themselves are orthogonal, but the coeffcient representation in terms of AOs is not, since AOs are not orthogonal (ie. MOs are not a simple rotation of AOs). The coefficient matrix C is bithogonal to S.C, where S is the AO overlap matrix: C^T . S . C = identity.

**Comment by Eureka10shen** [comment]
After using the ```compact=True``` command, the codes output the eri as a matrix with the shape as (mol.nao * mol.nao, mol.nao * mol.nao).
I want to ask the matrix element index corresponding to the two-electron integral
$$(ijkl) = \int\phi_i(\mathbf{r}_1)\phi_i(\mathbf{r}_1)\frac{1}{\mathbf{r}_{12}}\phi_k(\mathbf{r}_2)\phi_l(\mathbf{r}_2)$$
is it just ```[i * mol.nao + j] [k * mol.nao + l]``` ?
Thank you!!!

**Comment by hebrewsnabla** [comment]
yes, but you may have a typo -- `compact=False` will give you a shape like `(N*N, N*N)`, `compact=True` will give you `(N(N+1)/2, N(N+1)/2)`.

**Comment by Eureka10shen** [comment]
> yes, but you may have a typo -- `compact=False` will give you a shape like `(N*N, N*N)`, `compact=True` will give you `(N(N+1)/2, N(N+1)/2)`.

Yes, this is a typo, 😅. Thank you for your reply!!!
