### ISSUE TITLE
Could stability check return a bool variable for stable/unstable?

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#873]
For example, `uhf_stability` or `uhf_internal` only return a set of new MO (unchanged when wavefunction is stable). It would be much more convenient, when developing, if these functions also return a bool variable indicating the result of the stability check.

Only a few lines of codes need to be added at the end of each stability-check function. Here is an example
```
def uhf_internal(mf, with_symmetry=True, verbose=None):
    ...
    if e < -1e-5:
        log.note('UHF/UKS wavefunction has an internal instability.')
        nocca = numpy.count_nonzero(mf.mo_occ[0]> 0)
        nvira = numpy.count_nonzero(mf.mo_occ[0]==0)
        mo = (_rotate_mo(mf.mo_coeff[0], mf.mo_occ[0], v[:nocca*nvira]),
              _rotate_mo(mf.mo_coeff[1], mf.mo_occ[1], v[nocca*nvira:]))
        stable = False
    else:
        log.note('UHF/UKS wavefunction is stable in the internal stability analysis')
        mo = mf.mo_coeff
        stable = True
    return mo, stable
```

**Comment by jjgoings** [comment]
I'd second this request -- right now there is no way to automate stability testing and re-optimization of wave functions, which is extremely useful functionality. Otherwise one is stuck spamming scripts with repeated 
```
mo1 = mf.stability()[0]
dm1 = mf.make_rdm1(mo1, mf.mo_occ)
mf = mf.run(dm1)
mf.stability()
```
calls, which is inefficient and/or impractical for large systems and throughputs. A boolean flag would at least let us wrap the above calls in a loop with a proper termination.

**Comment by hebrewsnabla** [comment]
I'm going to open a PR to add the boolean flag.
