### ISSUE TITLE
2.0 is not on PyPI

### ISSUE THREAD

**Issue by yurivict** [pyscf/pyscf#933]
https://pypi.org/project/pyscf/

**Comment by theonov13** [comment]
Hi all, 

Is the PySCF v2.0.0a version (libxc 5.1.2) still not on pypi? 

https://pypi.org/project/pyscf/#history

Could it be a naming problem,
may cause by a misspelled release version (2.0a instead of 2.0.0a)?

https://github.com/pyscf/pyscf/commit/b76d2ceae0011d06b279f937bb36ce3c137dc57b

I found a pypi version called 2.0a0 

https://github.com/pyscf/pyscf/runs/2281914728?check_suite_focus=true#logs
https://test.pypi.org/project/pyscf/2.0a0/

which installs. 
However, it seems still not support for instance r2SCAN ('497,498')? 

```Bash
Failed to load library libtblis_einsum
XC functional 497 not found
```
A PySCF version properly installing from pip with support of newer libxc versions would be very nice to have. 

Best, 
Sebastian

**Comment by kaitrepte** [comment]
Hi there,

I was wondering about the same thing. 
There seems to be a new 2.0 version, but via pypi I do not get it.
Also, having the most current GitLab version of LibXC as a standard would
be nice for the future.

Best,
Kai

**Comment by verena-neufeld** [comment]
Hi @yurivict , has this been resolved?
