### ISSUE TITLE
Can't find source of randomness

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#982]
Hello everyone,
I am simulating a CuH molecule through an HF calculation and I would like to make the results reproducible (by now it fluctuates around the 10th decimal digit).
```
np.random.seed(0)

mol = gto.M(atom=[['Cu',(0,0,0)],['H',(0,0,1.46)]],basis='6-31g',symmetry='Coov',charge=0,spin=0,verbose=4)
mf  = scf.RHF(mol)

mf.kernel()
mf.analyze()
mf.stability()
```

I have fixed the numpy seed but it looks like it's not enough... I would really appreciate if someone could help me finding the randomness source and tell me how to fix it!
Thanks,
Martina

**Comment by verena-neufeld** [comment]
Unless I am mistaken, I believe the convergence tolerance might be set to 1e-10 by default, see
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L49 . If you require a greater amount of precision - maybe lowering this value by setting it explicitly when calling `mf.kernel` helps?

**Comment by fishjojo** [comment]
For a program run in parallel, rounding errors will add differently each time you run the program. If you run the calculation in serial (for pyscf, use only one thread: `export OMP_NUM_THREADS=1`), you should see exactly the same result every time.

**Comment by martinanibbi** [comment]
Hello, thank you very much for your suggestions!
I tried asking for a higher precision but the final result didn't change so much: I didn't say it in my opening comment but after a HF calculation I am doing a sort of Orbital Relaxation and I have noticed that tiny fluctuations in the HF energy cause much bigger fluctuations in the final result (from 1e-11 of HF to 1e-5 after the OR).
Unfortunately even by lowering the tolerance of HF I still get very big fluctuations (around 1e-6) which is still too much for my purposes.
Anyway, thank you @verena-neufeld because I never thought about changing those parameters and I for sure will use this information in the future!

Secondly, my code is not running in parallel and I added the following lines to the code :
```
import os 
os.environ["OMP_NUM_THREADS"] = "1"
```
This seemed to solve my problem as now I see exactly the same result every time, so thank yo very much to @fishjojo too!

**Comment by Majokux** [comment]
@martinanibbi
PySCF uses OpenMP (OMP) to parallelize operations, hence you see the change of behaviour as you export OMP_NUM_THREADS.
The non deterministic behaviour in parallel code arises since mathematical operations do not strictly commute in finite precision math, e.g. a + b + c can lead to a slightly different results than c + b + a, due to rounding.
In general we do not worry about this, since the resulting errors are much smaller than the accuracy we are interested in.
However, if your algorithm is sensitive to such small differences, this could indicate that it is badly conditioned. Just something to keep in mind.
